### ISSUE TITLE
Use rythmengine in view layer

### ISSUE THREAD

**Issue by mohsenk** [ninjaframework/ninja#104]
Hi
FreeMarker in not good chooice for a mvc solution.
Please look at to http://rythmengine.org/ WebSite.
Thanks

**Comment by raphaelbauer** [comment]
Hi,

rythm looks really good, and I already proposed the maintainers to create a plugin for Ninja to enable support.

On the other hand - what makes you think in particular that freemarker is not a good choice?

Thanks!

Raphael

**Comment by mohsenk** [comment]
Good work.
FreeMarker is not bad but ,
rythm is very flexbile ,
and have clear structure and good syntax.

**Comment by raphaelbauer** [comment]
True true. Freemarker is really mature and has everything we need. However, it is not statically typed and a lot slower than something like Rythm.

Contributions are really welcome :) Rythm should be easy to integrate :)

**Comment by raphaelbauer** [comment]
@sojin is working on it... https://github.com/ninjaframework/ninja-rythm
