### ISSUE TITLE
Flash getting cleared if static assets served in between dynamic page requests.

### ISSUE THREAD

**Issue by sojin** [ninjaframework/ninja#109]
Flash is supposed to be retained between subsequent request (at most one), but if any static asset is served in between, the Flash is getting cleared. 

Almost all web apps would need to serve numerous static assets to get the page rendered and this defeat the purpose of Flashing.

<code>FlashCookieImpl.save()</code> is clearing all the Flash cookies if the <code> outgoingFlashCookieData</code> is empty. We could add a flag (something like 'keepFlash') in Context and set it to <code>true</code> from the <code>AssetController</code> and check this flag in <code>FlashCookieImpl.save() </code> before clearing. 

Yes, ideally static assets should be served directly from a front end server (such as Nginx or Apache), but there are cases when we might not use them.

Cheers
Sojin

**Comment by raphaelbauer** [comment]
Hi Sojin,

good catch! You are absolutely right. Can you check if github.com/ninjaframework/ninja/pull/110 (https://github.com/ninjaframework/ninja/branches/bugfix-109-static-assets-should-not-handle-flash-scope) fixes the issue for you? I also added testcases to make sure that this issue does not happen again.

Thanks!

Raphael

**Comment by sojin** [comment]
Hi Raphael,

Thanks for the fix, its working for me. You may merge and close the issue.

Rgds
Sojin

**Comment by raphaelbauer** [comment]
done
