### ISSUE TITLE
JSONP in Results

### ISSUE THREAD

**Issue by nobullet** [ninjaframework/ninja#112]
It would be great to have JSONP in Results.

Results.jsonp("calback6570").render(object);

Will produce application/json  content type with body like this:

calback6570({...});

Serialization of the object is just like Results.json()

**Comment by raphaelbauer** [comment]
Hi @nobullet,

that would be perfect! Let me know if I can help.

Raphael

**Comment by raphaelbauer** [comment]
implemented by nobullet...
