### ISSUE TITLE
Freemarker coupling

### ISSUE THREAD

**Issue by kpacha** [ninjaframework/ninja#115]
why is ninja-core so coupled with freemarker?

I know freemarker is one of the most popular template engines, so making it the default choice is ok. But coupling the main application module with a single template engine is not the best option. I think it would better be just another module that you can add into your project dependencies. Or just a core dependency you could exclude in favor of the rythm/mustache/{name your favourite template} module or because your project does not need a template engine at all.

**Comment by raphaelbauer** [comment]
hi kpacha,

you can roll your won templating engine. while it is true that ninja-core ships with freemarker integration by default you can easily bind your own templating engine via a simple guice binding.

for instance sojin is currently implementing rythm as templating engine: https://github.com/ninjaframework/ninja-rythm this should give you some really good ideas how to do that.

internally the stuff works like that:
https://github.com/ninjaframework/ninja/blob/develop/ninja-core/src/main/java/ninja/template/TemplateEngineManagerImpl.java

explicit bindings always override the default bindings...

let me know if you got any other questions...

cheers,

raphael

**Comment by kpacha** [comment]
Hi,

I've been playing with the ninja-rythm module (nice work too!) and the ninja-mustache module is almost ready. I'm extending the test suite before sending a PR. In deed, I realised the coupling while I was working on it and, as you said, it is not a big deal. It's just that little dependency on the TemplateManagerImpl constructor... it is coupling the core with a template engine you must add to your dependencies even when it is unrequired because you will not use it (say you don't need any template engine because all your responses are JSON or XML). I know there must be some 'opinated' components so coupled with the framework that replacing them with other libraries is not a good option... but do you think this is the case?

As I said before, why don't ship the freemarker-related classes as a module, just like the rythm one? Is not the worst case scenario just adding one more dependency in our pom file? I'm sure I'm missing something...

**Comment by raphaelbauer** [comment]
Wohooo! mustache! Looking forward to it :)

Regarding submodules - you are absolutely right. On the other hand if
everything is packaged into one Maven module development is a bit
simpler...  But at some point it makes sense to decouple things more and
separate stuff into submodules...

If you think this should be changed raise your hands :)

Best,

Raphael

On Wed, Oct 23, 2013 at 12:22 AM, kpacha notifications@github.com wrote:

> Hi,
> 
> I've been playing with the ninja-rythm module (nice work too!) and the
> ninja-mustache module is almost ready. I'm extending the test suite before
> sending a PR. In deed, I realised the coupling while I was working on it
> and, as you said, it is not a big deal. It's just that little dependency on
> the TemplateManagerImpl constructor... it is coupling the core with a
> template engine you must add to your dependencies even when it is
> unrequired because you will not use it (say you don't need any template
> engine because all your responses are JSON or XML). I know there must be
> some 'opinated' components so coupled with the framework that replacing
> them with other libraries is not a good option... but do you think this is
> the case?
> 
> As I said before, why don't ship the freemarker-related classes as a
> module, just like the rythm one? Is not the worst case scenario just adding
> one more dependency in our pom file? I'm sure I'm missing something...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ninjaframework/ninja/issues/115#issuecomment-26859738
> .

## 

inc: http://ars-machina.raphaelbauer.com
tech: http://ars-codia.raphaelbauer.com
web: http://raphaelbauer.com

**Comment by kpacha** [comment]
@raphaelbauer, the ninja-mustache module is ready (https://github.com/kpacha/ninja-mustache). I didn't send a PR yet because there is an integration test I can't fix (NotFoundTest). Suggestions will be apreciated.

... and looks like nobody is interested in decoupling the default template engine.

**Comment by raphaelbauer** [comment]
Pretty nice!
I'll have a look the next days :+1: 
Cheers,

Raphael

**Comment by raphaelbauer** [comment]
Your test does not pass because you need the following section in the pom.xml of ninja-mustache:

```
    <build>
    <resources>
        <resource>
            <directory>src/main/java</directory>
            <includes>
                <include>**/*</include>
            </includes>
        </resource>
        <resource>
            <directory>src/main/resources</directory>
            <filtering>true</filtering>
            <includes>
                <include>**/*</include>
            </includes>
        </resource>
    </resources>
</build>
```

Otherwise resources inside the java directory won't get included in your jar :)

Let me know if that helps...

Nice work!

**Comment by kpacha** [comment]
@raphaelbauer, with your fix the test works like a charm!

Thanks!
