### ISSUE TITLE
Better internationalization support for intellij

### ISSUE THREAD

**Issue by amsz** [ninjaframework/ninja#118]
Ninja use 'messages.%s.properties' format to load i18n files, but intellij idea only automatically detect i18n files for 'messages_%s.properties' format. Intellij properties editor is a amazing, see: http://www.jetbrains.com/idea/features/i18n_support.html

Could ninja support config delimiter of i18n file in the feature?

**Comment by raphaelbauer** [comment]
Hi amsz,

that is a very good idea. It is the same with Netbeans. Do you have ambitions implementing the feature? I could point you to the parts of Ninja that need to be changed..

Thanks!

Cheers,

Raphael

**Comment by amsz** [comment]
OK, I will try it.

**Comment by raphaelbauer** [comment]
Added in develop => scheduled for 2.3.0. Thanks!
