### ISSUE TITLE
escape-html should escape apostrophe's

### ISSUE THREAD

**Issue by msmith-techempower** [ninjaframework/ninja#135]
I am building out the validation for the next round of benchmarks and came across the fortunes test for Ninja. The problem is that the apostrophe isn't escaped while quotes, amps, and lts/gts are. We are trying to stick with web-decided best practices and apostrophes are considered "should escape".
Example:

``` html
<a href='${untrustedData}'>Click Me!</a>
```

Since apostrophes can replace quotes for hrefs in this way, this if valid html but the following is an attacking input: `untrustedData = "' onclick='while(true){alert(\"hahaha\");}"`

**Comment by raphaelbauer** [comment]
Hi Mike,

very good catch! We fixed the issue and a new version is being released just now (2.5.0).

We are currently working on an improved version of our Ninja Techempower benchmarks, and you'll get a new PR (including the latest version of Ninja) soon.

Many thanks again and keep up the great work!

Cheers,

Raphael
