### ISSUE TITLE
Docu enhancement: Better description how rendering of objects works => especially why rendering a map does not work

### ISSUE THREAD

**Issue by raphaelbauer** [ninjaframework/ninja#148]
See also:
https://groups.google.com/forum/#!topic/ninja-framework/ojYT36l5tD8

**Comment by Nightforce** [comment]
Just flew high level from a MGMT perspective maybe the int. sys. engineering guide could help you to improve your docs - just google: incose full pdf

**Comment by Nightforce** [comment]
Edit: Just seen it's a tec point - forget my doc point :-)

**Comment by raphaelbauer** [comment]
kk. Closing this. Anyway - thanks for submitting and thinking about Ninja in terms of mgmt... :) That kind of feedback is always great!
