### ISSUE TITLE
@UnitOfWork yields java.lang.IllegalStateException: Work already begun on this thread.

### ISSUE THREAD

**Issue by raphaelbauer** [ninjaframework/ninja#157]
@Transactional works, but @UnitOfWork breaks

annotate any method with 
@Transactional 
@UnitOfWork
public Result myController() ...

and you'll get the exception described above.

Exception reported by @smallufo at https://groups.google.com/forum/#!topic/ninja-framework/XHrJU88tqkk

**Comment by raphaelbauer** [comment]
The bug is related to this issue it seems. Contrary to guice docs it is NOT supported to call unitOfWork.begin() multiple times...
https://code.google.com/p/google-guice/issues/detail?id=597

**Comment by raphaelbauer** [comment]
Fixed in branch https://github.com/ninjaframework/ninja/tree/bugfix-157-unitOfWork-does-not-work-sometimes. Please verify.

**Comment by bhuvangu** [comment]
Is this issue back in 4.0.4 ?
Our setup 

```
class A {
    @Inject
     Provider<EntityManager> entitiyManagerProvider;
    @Inject
     B b;
    @Transaction
     methodA(){
        //USE entitiyManagerProvider.get();
        b.methodB()
     }
}

class B{
    @Inject
     Provider<EntityManager> entitiyManagerProvider;
     @UnitOfWork
     methodB(){
     // USE entitiyManagerProvider
    }
}
```

WHen ever a call to A.methodA() happens it throw the same exception.
we are also working on getting a sample project to verify it
