### ISSUE TITLE
Logback defaults to Debug

### ISSUE THREAD

**Issue by svenkubiak** [ninjaframework/ninja#161]
Don't know if this is a bug or a feature, but if one has set custom logback files like logback.dev.xml and logback.prod.xml in application.conf and has removed the default logback.xml file, ninja picks up logback.dev.xml, but somehow defaults to debug. Even if only "info" is configured in logback.dev.xml

**Comment by raphaelbauer** [comment]
Could you post your logback files to reproduce the issue?

Thanks!

**Comment by svenkubiak** [comment]
I used the same content for the logback.dev.xml as in the default logback.xml

Just wanted to reproduce it on an empty project, but it looks like it doesn't have to do with the logback.xml file, rather than the jetty-maven-plugin. When I bump the jetty-maven-plugin to the latest stable version (9.1.3.v20140225). I get debug messages from netty. Shouldn't the logback config set this to info?

**Comment by raphaelbauer** [comment]
Maybe I just don't understand the problem.
I created a demo project from the simple archetype and configured it with two logging configurations: prod and dev. That works for me when running jetty:run, ninja:run and when using the standalone mode using a fat jar. The demo is here: https://github.com/raphaelbauer/ninja-logtest

In other projects that approach also works on the App Engine.

Can try if you can reproduce the problem on the demo project? Maybe I just got your question wrong...

Thanks!

Raphael

**Comment by svenkubiak** [comment]
Did you bump the jetty-maven-plugin in your empty project to 9.1.3.v20140225? Try that and just should get debug informations when using ninja:run.

**Comment by raphaelbauer** [comment]
Yes I tried that. E.g. ApplicationController's index method has two logger statements. And I can use the logging level of logback_dev.xml or locback_prod.xml to enable / disable certain levels...

**Comment by svenkubiak** [comment]
Did you delete the default logback.xml? I thinks this is the cruicial part. If i do that, it results in the attached screenshot.
![screenshot](https://f.cloud.github.com/assets/67564/2522740/559eecaa-b4c6-11e3-9686-5326d7557790.jpg)

**Comment by raphaelbauer** [comment]
Ok I see.

So the problem is that at the beginning you are getting debug messages, until after "a while" your correct logback settings are picked up?

**Comment by svenkubiak** [comment]
It looks that way. Try it yourself, by deleting the default logback.xml and setting the custom files in application.conf.

**Comment by raphaelbauer** [comment]
Ok. This is something that can be explained. Initialization of logging begins necessarily way before Ninja starts up. So if there is no default logback.xml - how does Logback init itself? The simple answer is that Logback will use a built in default configuration. And that's the config you are seeing and complaing about...

Once Ninja bootstrap kicks in logback gets reconfigured according to your application.conf.

That happens really really early, but this cannot happen before all potential logging statements in all of Jetty's codebase for instance.

If you don't like that you can still use " -Dlogback.configurationFile=/srv/conf/logback.xml" to init logback from the very beginning.

Does that make sense? You raised a good point - we should update the documentation accordingly.

**Comment by svenkubiak** [comment]
Ah, okay. Thats makes totally sense. Thanks for the explanation!
