### ISSUE TITLE
Doesn't save data in Session and FlashScope via injecting context

### ISSUE THREAD

**Issue by dim-s** [ninjaframework/ninja#162]
I tried to save some session data via injecting Context and getting getSession(), but it doesn't work:

```
@RequestScoped
public class MuloqotAuthCtrl extends BaseController {
     private final Context context;

     @Inject
     public MuloqotAuthCtrl(Context context) {
          this.context = context;
     }

     public Result oauth(Session session) {
            context.getSession().put("key", "value"); // doesn't work :(
            session.put("key", "value"); // it works!
     }
}
```

I noticed that `.getSession()` returns an object is not equal to injected object via method arguments.

I cannot always use the second way (method arguments). How should I store data in session via Guice and Injecting?

I use Ninjaframework 3.1.2

P.S. I also tried to inject the Session object (insteadof Context) and it doesn't work too.

**Comment by raphaelbauer** [comment]
The broad idea behind that is: @Inject is always application wide. Everything else (request based stuff) is specified inside the controller level. The controller is where your http request starts. Therefore you get all http request level information right there. There should not be a need for @RequestScoped.

The first way using @Inject Context is currently not supported. Ninja will "inject" request based objects into the controller. Your way to handle oauth(Session session) is the way to go - just extend it with public Result oauth(Session session, Context context)... 

There are for sure ways how to inject Context in a request based fashion, but these do not exist yet, and I personally do not have any use for them. If you want to implement something have a look at ContextImpl. You can theoretically create the Context from the HttpServletRequest afiak.

Out of curiosity: When do you need @RequestScoped?

If you have ideas how to improve the docs let us know. File a bug :) All contributions really welcome!

**Comment by dim-s** [comment]
It would be very convenient if I could use the Session class by injecting. For example, when I want to use some an authorization token in any place of my code, I cannot use the session class in every my controller method and then pass it onto other objects that I create and use. 

I'll try to implement this feature, when I'll have time. Thanks =)

**Comment by raphaelbauer** [comment]
On the other hand you can of course just pass the session around via a method :) 

Let me know if I can help with implementing the feature! A good starting point is for sure ninja-servlet and how the HttpServletRequest can be injected in request scope :)

Cheers

**Comment by imeszaros** [comment]
@dim-s,

if you are still interested, see how i worked around this: imeszaros/timetrack@282f1a892bdb2b40747b484e9bbc91801e21a315

Not tested well yet but looks like it's working.
