### ISSUE TITLE
Maven Download Problem

### ISSUE THREAD

**Issue by sahinyanlik** [ninjaframework/ninja#187]
I am getting this error while downloading 

Downloading: http://repo.maven.apache.org/maven2/asm/asm/3.2/asm-3.2.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by raphaelbauer** [comment]
Works for me. Maybe your network is flaky?

**Comment by raphaelbauer** [comment]
Closing this one. This it's not a problem - at least not one from Ninja.
