### ISSUE TITLE
Documentation result.template(...) description missing

### ISSUE THREAD

**Issue by raphaelbauer** [ninjaframework/ninja#193]
Javadoc is ok, but the docu does not write about it... we should add it...

**Comment by metacity** [comment]
The section "Rendering html" at [Basic concepts > Controllers](http://www.ninjaframework.org/documentation/basic_concepts/controllers.html) does explain the usage quite well imo.

**Comment by raphaelbauer** [comment]
you are right Mikka... maybe we need a better search function ;) thanks!

**Comment by metacity** [comment]
Heh, definitely ;P
