### ISSUE TITLE
Documentation: POST, DELETE, PUT examples

### ISSUE THREAD

**Issue by sappo** [ninjaframework/ninja#211]
Hi,

I really like the ninjaframework so far. But the documentation could be extended. For example I couldn't get DELETE or PUT routes working. Some examples would be nice! E.g. with some REST approach.

Regarding parameters in POST I really would appreciate more details on the matter. E.g. are parsing parameters into a class e.g. Contacts in the documentation, the only way to get parameter to a post method?

Thanks in advance, keep up the great work!

**Comment by sappo** [comment]
Okay, I did find an explanation in section "Argument extractors". Though there's no example for @Path. I do understand form parameters but what is meant by query parameters?

**Comment by raphaelbauer** [comment]
Hey Sappo,

docs improvements are always welcome :) Ninja is a community effort after all - and if you find time to contribute some examples that would be great!

Regarding help and advice - please use our mailing list. Lots of helpful and friendly people :)
Check out https://groups.google.com/forum/#!forum/ninja-framework or ninja-framework@googlegroups.com - the mailing list is a lot better than the issues tracker for figuring stuff out :)

Cheers,

Raphael

**Comment by sappo** [comment]
Once I get a deeper understand I'll most certainly thinking about improving the documentation.
