### ISSUE TITLE
JPA page is not internally consistent

### ISSUE THREAD

**Issue by madebyjeffrey** [ninjaframework/ninja#215]
On the page http://www.ninjaframework.org/documentation/working_with_relational_dbs/jpa.html it shows   a persistence unit name:

```
ninja.jpa.persistence_unit_name=mypersistenceunit
```

and 

```
ninja.jpa.persistence_unit_name=dev_unit
%test.ninja.jpa.persistence_unit_name=test_unit
%prod.ninja.jpa.persistence_unit_name=prod_unit
```

But later in the XML it shows:

   <persistence-unit name="postgresql" transaction-type="RESOURCE_LOCAL">

and

```
<persistence-unit name="prod_unit" transaction-type="RESOURCE_LOCAL">
```

It would be nice if both of these files lined up and were explicit in how they are related. I spent the good part of an afternoon completely missing what was wrong with an application after following this page.

Related is that the file  META-INF/persistence.xml should be located under src/main/java instead of related *-INF directories, my mistakes in interpreting this led me to put it in the wrong place.

**Comment by raphaelbauer** [comment]
Hey @iaefai , 

thanks for the report... You can easily improve the documentation without checking out a single line of code: Simply move to https://github.com/ninjaframework/ninja/blob/develop/ninja-core/src/site/markdown/documentation/working_with_relational_dbs/jpa.md click on "edit" and propose an improvement!

Let me know if we can help!

Cheers,

Raphael for Team Ninja

**Comment by mikehearn** [comment]
This can be closed now.

**Comment by raphaelbauer** [comment]
Thanks - that's right sir!
