### ISSUE TITLE
Incomplete Copyright

### ISSUE THREAD

**Issue by eiryu** [ninjaframework/ninja#218]
http://www.ninjaframework.org

There is no organization name at footer.
`Copyright © 2014. All rights reserved.`

**Comment by raphaelbauer** [comment]
yes. should be fixed. thanks :)

**Comment by eiryu** [comment]
It has not been fixed yet.
I meant 'web site footer copyright', but #232 fixed 'pom.xml'.

**Comment by raphaelbauer** [comment]
#232 also fixes the website because it is generated by the pom.xml in ninja-core. So that's pretty cool :) thanks @zephiransas and thanks @eiryu for reporting! :D

**Comment by eiryu** [comment]
Oh, sorry. Thanks!

**Comment by raphaelbauer** [comment]
no worries :) it's always great having someone watching issues and raising hands when something might be wrong! :)
