### ISSUE TITLE
Date not converted (POJO Param)

### ISSUE THREAD

**Issue by pedro-stanaka** [ninjaframework/ninja#220]
When one try to pass a Bean as a parameter to a Controller, if this bean has a field that is of type java.sql.Date Ninja will throw the following error:

```
 ERROR ninja.utils.SwissKnife - No converter found to convert class java.sql.Date. Returning null. You may want to extend the class.
```

For example:

Controller bit:

``` java
    @Transactional
    public Result createPerson(@JSR303Validation
                               Person person,
                               Validation validation, Context context){
```

Where Person is the bean: 

``` java
public class Person {


    @Size(min = 5)
    public String name;

    @NotEmpty
    @Pattern(regexp = "^\\d{3}\\.\\d{3}\\.\\d{3}\\-\\d{2}$")
    public String docNo;

    public Date birthDate;

    @NotEmpty
    public String nickname;

    @Override
    public String toString() {
        return "Person{" +
                "name='" + name + '\'' +
                ", docNo='" + docNo + '\'' +
                ", birthDate=" + birthDate +
                ", nickname='" + nickname + '\'' +
                '}';
    }
}
```

Is there a scheduled fix for this or some workaround that I could take (e.g. Which class should I extend?) ?

Best regards.

**Comment by raphaelbauer** [comment]
The class is that one:
https://github.com/ninjaframework/ninja/blob/develop/ninja-core/src/main/java/ninja/utils/SwissKnife.java

You'd need to extend method "convert" so that it supports sql.Data.

Let me know if we can help :)

**Comment by pedro-stanaka** [comment]
But, in order to make the method `java public static <T> T convert()` support java.sql.Date I would have to extend the inner class `java Converter` as well, wouldn't I?

And since the inner class is private I can't. Other thing that I can't understand is how I tell Ninja to use my extended class instead of ninja.utils.SwissKnife.

What I've accomplished so far was to create the class that extends ninja.utils.SwissKnife and inside the method convert check if the target type of the conversion is sql.Date, but my conscience keep telling me that it sounds wrong. Check if that's OK, please:

``` java
package utils;

import com.google.inject.Inject;
import ninja.utils.NinjaProperties;
import ninja.utils.SwissKnife;
import org.joda.time.DateTimeZone;
import org.joda.time.LocalDate;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;

import java.sql.Date;

public class SwissKnifeDate extends SwissKnife {

    private final static String ptBrDateFormat = "dd/MM/yyyy";
    private final static String enDateFormat = "yyyy/MM/dd";
    private static final DateTimeZone jodaTzUTC = DateTimeZone.forID("UTC");
    @Inject
    private static NinjaProperties ninjaProperties;

    public static <T> T convert(String from, Class<T> to) {

        if (to.getName().equals("java.sql.Date")) {
            String languages = ninjaProperties.get("application.languages");
            DateTimeFormatter formatter;
            if (languages != null) {
                if(languages.startsWith("pt-BR"))
                    formatter = DateTimeFormat.forPattern(ptBrDateFormat);
                else
                    formatter = DateTimeFormat.forPattern(enDateFormat);
            } else {
                formatter = DateTimeFormat.forPattern(enDateFormat);
            }
            LocalDate dt = formatter.parseLocalDate(from);
            T t = (T) new Date(dt.toDateTimeAtStartOfDay(jodaTzUTC).getMillis());
            return t;
        } else {
            return SwissKnife.convert(from, to);
        }
    }

}
```

**Comment by gitblit** [comment]
I'd like to see Date/Time support baked-into Ninja based using some sort of a conversion annotation which allows you to specify both format and timezone.  When I get time I'll push a PR for this.... unless @pedro-stanaka would like to first.

**Comment by pedro-stanaka** [comment]
@gitblit I'd be pleased to submit a PR with some of these changes that you said, but I'm afraid I don't have enough Java nor Ninja knowledge to this. I don't even understand what is the request/response cycle inside Ninja classes. But if someone provide me some guidance, I think I could make this happen.

**Comment by raphaelbauer** [comment]
@pedro-stanaka I think you have to create a pull request and add support for sql.Date in Ninja's SwissKnife to make that work. Maybe another option is to use Jackson to parse post form requests as well (just an idea - not sure if that works - but we don't want to reinvent the wheel).

How do you currently send the request... it's a post request from a form - right?

**Comment by pedro-stanaka** [comment]
Yes It is POST from a form. I'll read the code of the framework and I'll try to do this PR. I'll investigate the use of Jackson.

**Comment by pedro-stanaka** [comment]
I made the PR, It is not as complete as @gitblit mentioned, but it is something. Please make a code review and if I did something wrong let me know and I'll fix it.

Thanks for the support.

**Comment by pedro-stanaka** [comment]
Since the PR was merged I'm marking this as closed.
