### ISSUE TITLE
Organize imports

### ISSUE THREAD

**Issue by svenkubiak** [ninjaframework/ninja#245]
The maven projects for the framework could appreciate from an automatic "orgnaized imports". In the core project this for example, all classes have unused imports. 

Please let me know what you think.

Cheers,
Sven

**Comment by gitblit** [comment]
I agree.  Plus I often run into formatting differences between the source content and the Eclipse rules.

It would be good to reformat at the same time as organizing imports.

**Comment by raphaelbauer** [comment]
Totally agree :) There shouldn't be any not used imports!

**Comment by svenkubiak** [comment]
The formatting is another thing I have in mind, but lets go with the imports first. I'll create a pull request :-)
