### ISSUE TITLE
Add protocol to ninja.Context

### ISSUE THREAD

**Issue by chrsin** [ninjaframework/ninja#257]
It would be really nice to be able figure out the protocol from a Context object. I need it for an appengine project where i want to make a Filter that ensures an error occurs when trying to invoke my webservices with http.

I seem to recall from your documentation that you feel the responsibility of ssl is at the hands of the container. But as far as i can tell, on appengine you are only able to force a redirect to https on the urls. Not make them fail.

The reason i want it to fail is to make sure users of my API cant configure their clients wrong and invoke my webservices with http.

Thanks for a GREAT framework!

**Comment by raphaelbauer** [comment]
Hi chrsin, 

Ninja's context doen't have support for this right now. The solution is to provide something like "context.getScheme()" that's straight forward by modifying Context and ContextImpl (and writing a test to make sure the feature works).

That would make a really nice contribution... What do you think?

Cheers,

Raphael

**Comment by chrsin** [comment]
I think i need to remember this is open software.

thanks for reminding me. :)

**Comment by raphaelbauer** [comment]
Hey chrisin - could you please verify the merge and close this issue? Thanks for your contribution!

**Comment by chrsin** [comment]
Looks good!

Your very welcome
