### ISSUE TITLE
[Feature request] Ability to set a global filter

### ISSUE THREAD

**Issue by noguespi** [ninjaframework/ninja#259]
support for a global filter used in every request. 

The actual method consist to create a BaseController using the "global" filter and to extend BaseController in every controller. 

However, the filter may not be called everytime, there are workaround but not clean. See [mailing list](https://groups.google.com/d/msg/ninja-framework/4iPUw8TK9io/gQ1s95RKBncJ) for more details.

**Comment by jlannoy** [comment]
Done. http://www.ninjaframework.org/documentation/basic_concepts/filters.html
