### ISSUE TITLE
Message getWithDefault() and get() don't return same the same result

### ISSUE THREAD

**Issue by thibaultmeyer** [ninjaframework/ninja#261]
Hi,

I have an issue on Ninja 4 with the internationalization system. The method getWithDefault(...) don't return the same result than get(...).
###### messages_fr.properties

```
demo = C'est le sens de la vie
```
###### messages.properties

```
demo = It's the meaning of life
```
###### MyController.java

```
@Singleton
public class ApplicationController {
    @Inject
    private Messages msg;

    public Result index(Context ctx) {
        Optional<Result> optResult = Optional.absent();

        LOG.info(msg.getWithDefault("demo", "demo", context, optResult));
        LOG.info(msg.get("demo", context, optResult).get());
        return Results.html();
    }
}
```
###### Output

```
[2014-11-26 20:15:50] INFO  - ApplicationController - Cest le sens de la vie
[2014-11-26 20:15:50] INFO  - ApplicationController - C'est le sens de la vie

[2014-11-26 20:15:50] INFO  - ApplicationController - Its the meaning of life
[2014-11-26 20:15:50] INFO  - ApplicationController - It's the meaning of life
```

The apostrophe is just ignored when I use getWithDefault() method. It's embarrassing because, the get() method raise an exception rather than return key when translation was not found.

**Comment by raphaelbauer** [comment]
Very good catch. Thanks for the report!

Just created testcases and a fix for it. Could you please verify: https://github.com/ninjaframework/ninja/pull/262?

Thanks!

Raphael

**Comment by thibaultmeyer** [comment]
Thank you for your response. The patch works and apostrophes are displayed correctly with get () and getWithDefault ()

I encountered a problem when generating .jar on Windows platform. Unit tests fail on the second subproject (ninja-core) and all other are skipped. Compilation works fine on Linux platform (tested on Debian 7 x64)

###### software version

```
C:\Users\Thibault\Documents\Developpement\ninja>java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

C:\Users\Thibault\Documents\Developpement\ninja>mvn --version
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T22:58:10+02:00)
Maven home: C:\apache-maven-3.2.3\bin\..
Java version: 1.8.0_25, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_25\jre
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "dos"
```

###### Output log

mvn compile : http://pastebin.com/naAAcV6a
mvn package : http://pastebin.com/8PF5Q4QA

**Comment by raphaelbauer** [comment]
I am closing this then :)

Could please create a new bug for the second thing you are describing? Then we can schedule an investigation :)
