### ISSUE TITLE
Fix name of import 

### ISSUE THREAD

**Issue by fzakaria** [ninjaframework/ninja#269]
```
public static final String APPLICATON_JSON = "application/json";
public static final String APPLICATON_JSONP = "application/javascript";
```

The word APPLICATION is missing the `I`
I recommend probably adding @Deprecated and adding the missing static public variables with correct naming

**Comment by raphaelbauer** [comment]
Yea. That's a stupid mistake. Can you verify https://github.com/ninjaframework/ninja/pull/271 ? Thanks for reporting the glitch!

**Comment by magikid** [comment]
It looks like this issue can be closed now because of the merge.

**Comment by raphaelbauer** [comment]
👍 Thanks :)
