### ISSUE TITLE
pom.xml in maven example has bug

### ISSUE THREAD

**Issue by fzakaria** [ninjaframework/ninja#273]
All the pom.xml in the example configurations such as [this example](https://github.com/ninjaframework/ninja/blob/develop/ninja-servlet-archetype-simple/src/main/resources/archetype-resources/pom.xml#L56)

```
               <configuration>
                        <contextPath>/</contextPath>
                    <stopKey>stop</stopKey>
```

It should be however (notice webApp owning element)

```
               <configuration>
                    <webApp>
                        <contextPath>/</contextPath>
                    </webApp>
                    <stopKey>stop</stopKey>
```

Reference: http://www.eclipse.org/jetty/documentation/9.2.2.v20140723/jetty-maven-plugin.html#configuring-your-webapp

**Comment by fzakaria** [comment]
It still seems to work however IntelliJ was giving annoying error message

**Comment by raphaelbauer** [comment]
Thanks for pointing out the problem :) Could your verify that https://github.com/ninjaframework/ninja/pull/276 fixes the issue? Thanks!

**Comment by magikid** [comment]
@fzakaria I'm going through some older issues and saw that this one is still open.  Does #276 fix the issue you were seeing in Intellij?

**Comment by fzakaria** [comment]
I don't have context anymore.  Feel free to close.

**Comment by raphaelbauer** [comment]
👍 Thanks!
