### ISSUE TITLE
SuperDevMode does not support web.xml.

### ISSUE THREAD

**Issue by ekirin** [ninjaframework/ninja#282]
I added Apache Shiro to Ninja project by using servlet bridge feature and have defined shiro listener at web.xml. But SuperDevMode doesn't support web.xml (and test too). As result it couldn't use SuperDevMode and run tests.

**Comment by ekirin** [comment]
If this feature interesting I can create a pull request.

**Comment by raphaelbauer** [comment]
sounds great :) If we can help let us know!

**Comment by magikid** [comment]
@ekirin I'm cleaning up some old issue and saw this was still open.  Are you still interested in this?
