### ISSUE TITLE
403 Forbidden not working

### ISSUE THREAD

**Issue by svenkubiak** [ninjaframework/ninja#293]
It looks like 403 Forbidden is not handled correctly. 

Steps to reproduce:
- Create an app based on the simple archetype
- Start app
- Open localhost:8080 which shows the index page "Hello World"
- Change Result in Index-Controller from Results.html(); to Results.forbidden();
- Open localhost:8080 which shows the index page "Hello World" again

The Browser does send a 403 status code for the request, but the accepted result would be the system page showing 403forbidden.ftl.html.

Tryed this in SuperDevMode.

**Comment by svenkubiak** [comment]
Update: Checked the code and its okay. The fobidden(), ok(), etc. actually only set the status code. I ended up copying the getForbiddenResult() method from NinjaDefault.

What do you think of some convenient Result methods that do what NinjaDefault does?

**Comment by raphaelbauer** [comment]
Imho forbidden() works the way it should work. It simply alters the http code of the response.

Regarding NinjaDefault - that's actually the way it is supposed to be. Simply inject Ninja into your controller and use the getXYZ method to return the correct result for your error.

**Comment by svenkubiak** [comment]
Totally agree. Took me some time to get my head around this.

**Comment by raphaelbauer** [comment]
Is documentation missing?

**Comment by svenkubiak** [comment]
No, no. Still having some play paradigmas in my head ;-)

**Comment by raphaelbauer** [comment]
okay :)
