### ISSUE TITLE
Error 500 on JSON form submission

### ISSUE THREAD

**Issue by thibaultmeyer** [ninjaframework/ninja#303]
Hi,

They are an issue on the JSON request parsing. If JSON document is empty, the server parser crash (missing  try/catch ?) and return the error code 500.

If I replay the same scenario with an standard request (application/x-www-form-encoded) and no data : the validation process works and Validation object contain error like "this field can't be null".

It could be nice to have the same behavior regardless of the chosen method (JSON, Form-Encoded, XML) and in all case, don't raise error 500 during the form validation process.

_I have tested with cURL and Chrome extension : Advanced Rest Client_
##### My form object

```
public static class ProfileForm {
    @NotNull
    @NotBlank
    public String first_name;

    @NotNull
    @NotBlank
    public String last_name;
}
```
##### ApplicationController

```
public Result updateProfile(Context ctx, @JSR303Validation ProfileForm f, Validation v) {
    if (!v.hasViolations()) {
        // No errors : return object
        return Results.jsonp().render(f);
    }

    // Errors
    return Results.jsonp().render(v);
}
```
##### Example 1 (JSON) : OK (Validation::hasViolations() return false)

```
{
    first_name : "John",
    last_name : "Smith"
}
```
##### Example 2 (JSON) : OK (Validation::hasViolations() return true)

```
{
}
```
##### Example 3 (JSON) : CRASH (http error 500)

```
// empty JSON (length: 0)
```

Console output :

```
13:06:19.311 [qtp66233253-15] ERROR n.bodyparser.BodyParserEngineJson - Error parsing incoming Json
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
...
at ninja.bodyparser.BodyParserEngineJson.invoke(BodyParserEngineJson.java:51) ~[ninja-core-4.0.5.jar:na]
at ninja.servlet.ContextImpl.parseBody(ContextImpl.java:279) [ninja-servlet-4.0.5.jar:na]
at ninja.params.ArgumentExtractors$BodyAsExtractor.extract(ArgumentExtractors.java:299) [ninja-core-4.0.5.jar:na]
at ninja.params.ValidatingArgumentExtractor.extract(ValidatingArgumentExtractor.java:40) [ninja-core-4.0.5.jar:na]
```
##### Example 4 (Form Encoded) : OK (Validation::hasViolations() return false)

```
first_name=John&last_name=Smith
```
##### Example 5 (Form Encoded) : OK (Validation::hasViolations() return true)

```
first_name=John&unknown=bam
```
##### Example 6 (Form Encoded) : OK (Validation::hasViolations() return true)

```
// no data submitted
```

**Comment by raphaelbauer** [comment]
I agree that parsing json in a json request should not lead to a 500. I'd say it should lead to a 400 bad request... If it's no json you can not validate it - how should you. That would still be different to the form encoded request, though - but that also makes sense because an empty form encoded request is valid...

**Comment by thibaultmeyer** [comment]
hi,

of course, in this case, a 400 would be nice.

**Comment by raphaelbauer** [comment]
Feel free to submit a PR for that. Let me know if I can help (you can also ping us on our mailing list :) )...  Cheers, Raphael

**Comment by thibaultmeyer** [comment]
ok, i will working on this week end.

**Comment by thibaultmeyer** [comment]
Hi,

I'm not sure how return a 400 from the body parser. But in the pull request 325. I have fixed the first part of the problem and hasViolations() now return the right value.
