### ISSUE TITLE
Default system view templates linking to wrong "home page" due to contextPath not being used.

### ISSUE THREAD

**Issue by jfendler** [ninjaframework/ninja#307]
The default FreeMarker templates in ninja-core provide a link to `href="/"`. While this is fine if running without a set context, this points to a wrong URL (outside the application) when used with a context for the application.

All `href="/"` attributes in ninja-core's views/*ftl.html files should be changed to `href="${contextPath}/"` instead.

**Comment by raphaelbauer** [comment]
That's absolutely true. Would you be interested in contributing a fix?

**Comment by jfendler** [comment]
I'll get onto it tomorrow when I find some minutes.

Another thing I just noticed about the templates are the hardcoded strings (e.g. "Back to Homepage"), which should probably be read from messages for localisation?!

**Comment by raphaelbauer** [comment]
That's fixed with your contribution (#308). Thanks Jens!

**Comment by patriciclobo** [comment]
How can we configure the auth.redirect with contextpath?

**Comment by raphaelbauer** [comment]
What do you mean by that?

**Comment by patriciclobo** [comment]
Sorry take so long to respond.

I'm using the authentication module for ninja and in my application.conf 
I have auth.login.redirect=/login to redirect anyonethat isn't 
authenticated to login page.

When I'm running in localhost that isn't a problem, but when I try to 
run the application in a server with base path different than root it 
cant´t find the correct path, needs the contextPath.

**Comment by raphaelbauer** [comment]
I'd suspect that this is more a question for the author of the authentication module...
