### ISSUE TITLE
Ninja + Stork integration how-to

### ISSUE THREAD

**Issue by jjlauer** [ninjaframework/ninja#309]
Love the framework and I recently wrote a quick blog post about integrating Ninja with an "after-build" Java tool called Stork.  Compiling Ninja as a stand-alone server is straight-forward, but I find the maven assembly plugin cumbersome to actually get it to run in production. Stork's maven plugin helps fill in that gap, add start/stop/run scripts, etc.

The blog post is here: http://fizzed.com/blog/2015/01/using-stork-deploy-production-ninja-framework-app

The example app is here: https://github.com/fizzed/java-ninja-stork-demo

If you find it as useful as I have -- others may benefit and you are free to add it to http://www.ninjaframework.org/documentation/deployment/getting_started.html if you'd like.

**Comment by raphaelbauer** [comment]
That's pretty awesome!  Would you mind posting the message to our mailing list, too? I guess not many people are reading the issue tracker :( Thanks!
