### ISSUE TITLE
Cookies limited to application context

### ISSUE THREAD

**Issue by jfendler** [ninjaframework/ninja#310]
Hi Ninjas,

I'm currently deploying the same ninja application in multiple contexts on one application server. While doing so I've run into some (currently minor) issues with Ninja's cookie path values.

Currently, the cookies' path seem to be set to `"/"` throughout Ninja, where I believe it should rather be `context.getContextPath() + '/'`. 

Any opinions on this, or some feature I'm missing in this regard?

**Comment by raphaelbauer** [comment]
I think that makes total sense. Would you be interested in contributing some code?

**Comment by jfendler** [comment]
The PR is here: https://github.com/ninjaframework/ninja/pull/312.

**Comment by magikid** [comment]
The bug report can be closed as the associated PR has already been merged in.
