### ISSUE TITLE
Jars on maven central contain .java files

### ISSUE THREAD

**Issue by jjlauer** [ninjaframework/ninja#315]
Looks like ninja-core .jar (for at least 4.0.5) contains .java files as well as compiled .class files.  The other artifacts from the project don't.  Just wondering if this was an accident or intended?

https://github.com/ninjaframework/ninja/pull/316

**Comment by jjlauer** [comment]
https://github.com/ninjaframework/ninja/pull/316

**Comment by raphaelbauer** [comment]
fixed by #316
