### ISSUE TITLE
JSR validation language

### ISSUE THREAD

**Issue by thibaultmeyer** [ninjaframework/ninja#320]
Hi,

I using, according to your documentation, the JSR validation to validate a form submited via POST. But I have an issue with your "Validation" object : all error message are translated in the Operating System locale (my dev env is running on French  Windows 8.1) even when I specify 'Accept-Language: en" on the POST request.

Is it possible to force JSR error message to be compliant with the requested language ? or use the Ninja internal i18n system.

**ApplicationController.java**

```
public static class OAuth2ResultForm {
    @NotNull
    @NotBlank
    public String code;

    @NotNull
    @NotBlank
    public String result;
}

public Result oauth2callback(Context ctx, @JSR303Validation OAuth2ResultForm f, Validation v) {
    return Results.jsonp().render(v);
}
```

**JSONP response (Request => Accept-Language: en , no field submitted in the request body)**

```
onResponse({"fieldViolations":[],"generalViolations":[],"beanViolations":[{"field":"code","constraintViolation":{"messageKey":"ne peut pas être nul","fieldKey":null,"defaultMessage":null,"messageParams":[null]}},{"field":"result","constraintViolation":{"messageKey":"ne peut pas être nul","fieldKey":null,"defaultMessage":null,"messageParams":[null]}},{"field":"result","constraintViolation":{"messageKey":"ne peut pas être vide","fieldKey":null,"defaultMessage":null,"messageParams":[null]}},{"field":"code","constraintViolation":{"messageKey":"ne peut pas être vide","fieldKey":null,"defaultMessage":null,"messageParams":[null]}}]})
```

Error message : 

```
"messageKey":"ne peut pas être vide"
```

All error messages are in French (My computer running on a French version of Windows 8.1). Is it possible to Ninja to force JSR validation to use the language requested by the client (Accept-Language) ? Or to force manually from code before validate form ?

**Comment by thibaultmeyer** [comment]
Hi,

I'm working on a patch to get JSR 303 validation error message in the right language (by using the variable Accept-Language from the header request).

The modifications take place in the static JSRValidator class located in 

```
ninja-core\src\main\java\ninja\validation\Validators.java
```

In order to complete this patch, I have to use the method _getAcceptLanguage()_ from the NinjaContext object. But I can't get instance of this object; I have used the _Inject_ annotation but the variable is alway null.

Why the injection fail ? is there an alternative approach to get the Accept-Language data ?

```
public static class JSRValidator implements Validator<Object> {

    @Inject
    ninja.Context ninjaContext;

    @Override
    public void validate(Object value, String field, Validation validation) {
        if (value != null) {
            final ValidatorFactory validatorFactory = javax.validation.Validation.buildDefaultValidatorFactory();
            final javax.validation.Validator validator = validatorFactory.getValidator();
            final Set<javax.validation.ConstraintViolation<Object>> violations = validator.validate(value);
            final Locale localeToUse = (ninjaContext == null) ? Locale.getDefault() : Locale.forLanguageTag(ninjaContext.getAcceptLanguage().split(",", 2)[0]);

            for (javax.validation.ConstraintViolation<Object> violation : violations) {
                final String violationMessage = validatorFactory.getMessageInterpolator().interpolate(
                        violation.getMessageTemplate(),
                        new SimpleContext(value, violation.getConstraintDescriptor()),
                        localeToUse
                );

                //final String violationMessage = violation.getMessage();
                final ConstraintViolation constraintViolation = ConstraintViolation.create(violationMessage, violation.getInvalidValue());
                validation.addBeanViolation(new FieldViolation(violation.getPropertyPath().toString(), constraintViolation));
            }
        }
    }

    @Override
    public Class<Object> getValidatedType() {
        return Object.class;
    }

}
```

**Comment by raphaelbauer** [comment]
That does not work that way. We have to get hold of the context inside the validate method.

eg change the signature of the method (and deprecate the old one):

```
public void validate(Object value, String field, Validation validation, Context context) 
```

That's just an idea - there may be better ways how to solve this...

**Comment by thibaultmeyer** [comment]
thanks for help, I will investigate on this idea.

**Comment by raphaelbauer** [comment]
Would you mind verifying that everything works and closing this bug afterwards? Thanks!

**Comment by thibaultmeyer** [comment]
Everything seems to be working fine.
