### ISSUE TITLE
Wrong code in users guide on i18n topic

### ISSUE THREAD

**Issue by limnin** [ninjaframework/ninja#326]
At http://www.ninjaframework.org/documentation/internationalization.html 
wrong code:
`"localized message1: " + msg.get("casinoRegistrationTitle", language)`
correct code:
`"localized message1: " + msg.get("casinoRegistrationTitle", language).get()`

Please, correct.

**Comment by jjlauer** [comment]
The docs are actually in the github repo.  I'm sure the maintainers would appreciate it if you submitted a pull request to help fix it.  Just follow the github instructions on how to do a pull request and edit up this file:

https://github.com/ninjaframework/ninja/blob/develop/ninja-core/src/site/markdown/documentation/internationalization.md

**Comment by raphaelbauer** [comment]
Hey @limnin , 

first of all thanks for your report! I fixed it.
And Joe is right - it's really simple to make changes - just add your changes and create a pull request. Once it's merged you got your first contribution! Ninja is a community project - every helping hand is great for all of us!
