### ISSUE TITLE
Problem when using AuthenticityToken in Fluentlenium

### ISSUE THREAD

**Issue by svenkubiak** [ninjaframework/ninja#327]
@raphaelbauer 

Hey Raphael,

although the new Authenticity-Checks works as planed, I am having some Problems when using Fluentlenium to test my applications. From debugging I can confirm that the AuthenticityToken is passed to the template and is passed to the controller method correctly. But it looks like the method seesion.getAuthenticityToken returns a different token on the next request because they don't match. I think that the token is created when a page is called in fluentliuem, but on the next request the session is gone and the token is regenerated - even if you do this in the same test clas. Like I said, the problem only occurs when using Fluentlenium. "Normal" SuperDev- and Prod-Mode works well.

Do you have any idea where to dig into this, so I can create a bugfix?

Cheers,
Sven

**Comment by raphaelbauer** [comment]
no idea what the problem is.

Debugging should be easy though...
Start in class NinjaFluentLeniumTest. All the "magic" (no magic) happens here:

```
public WebDriver webDriver = new HtmlUnitDriver();
```

You can change that to the Firefox driver to see if there is a difference. It would be also interesting to see if 

```
public WebDriver webDriver = new HtmlUnitDriver(true); 
```

(enabling js) changes anything...

You can check the cookies imho via webDriver.manage().getCookies() or something...

**Comment by raphaelbauer** [comment]
there is also a new fluentlenium version (0.10.3). Maybe there is a bug in the old version (I doubt it...). But you should try to use the latest version...

**Comment by svenkubiak** [comment]
Thanks for the tip with the cookies. I narrowed it done, but haven't fix it yet.

```
    goTo(getServerAddress() + "/");

    //no cookies set at this point

    fill("#username").with("xxx");
    fill("#userpass").with("xxx");
    click("#login");

    assertTrue(pageSource().contains("foo")); //fails due to authenticity fail
```

What actually works is

```
    goTo(getServerAddress() + "/");

    //no cookies set at this point

    fill("#username").with("xxx");
    fill("#userpass").with("xxx");
    click("#login");

    goTo(getServerAddress() + "/");

    //cookies are set at this point

    fill("#username").with("xxx");
    fill("#userpass").with("xxx");
    click("#login");

    assertTrue(pageSource().contains("foo")); //works fine
```

It looks to me like the ninja session-cookie is not set on first request.
... or I am totally on the wrong track here.

UPDATE: Could it be possible that when the ninja session-cookie is created a new authenticity token is generated?

**Comment by raphaelbauer** [comment]
authenticity token is created once per session imho.

You can try to run the tests with a FirefoxDriver to see if it is a HtmlUnit problem...
It may also be the case that click("#login"); and the subsequent verify is too fast. Are you sure that click(#login) really blocks until the new page is loaded? Not sure. Sometimes selenium got some nasty timing issues...

**Comment by svenkubiak** [comment]
Found the problem, and it is unfortunately not Fluentlenium related.

When context.getSession.getAuthenticityToken() is called in the new TemplateEngineFreemarkerAuthenticityFormDirective it creates the AuthenticityToken for adding the hidden input field, but it does not create a session cookie. When context.getSession.getAuthenticityToken() is called in a controller or filter the session cookie with a "permanent" AuthenticityToken is created.

So when opening for example a login page with <@authenticityForm/> you get a new AuthenticityToken every time you reload the page. Upon submit, ninja will run into AuthenticityFiler (if you used FilterWith of course), call context.getSession.getAuthenticityToken(), create the cookie, but fails with a Forbidden page as it doesn't know the submitted authenticityToken. Upon next opening auf the login page, the authenticityToken from the session cookie will be used and everything works fine.

Any hints on why this works in filters and controllers, but not when called from TemplateEngineFreemarkerAuthenticityFormDirective?

A quick workaround would be to have a second filter (used at the method with the calling form) that just calls context.getSession.getAuthenticityToken(), but that would IMHO really be a quick fix.

**Comment by raphaelbauer** [comment]
Hey Sven,

I think I know where the problem may come from:

in file TemplateEngineFreemarker

try to move line 

```
ResponseStreams responseStreams = context.finalizeHeaders(result);
```

some lines below like that:

```
            StringWriter buffer = new StringWriter(64 * 1024);
            freemarkerTemplate.process(map, buffer);
            ResponseStreams responseStreams = context.finalizeHeaders(result);
            Writer writer = responseStreams.getWriter();
            writer.write(buffer.toString());
            writer.close();
```

This may solve the problem. If it does we need a test against it...

**Comment by svenkubiak** [comment]
Yub, that does the trick ;-) Thanks.

I'll add a test and create a PR.

**Comment by raphaelbauer** [comment]
yea!

**Comment by svenkubiak** [comment]
Confirmed working with latest Snapshort.
