### ISSUE TITLE
Can't bind list from post

### ISSUE THREAD

**Issue by gabrielhora** [ninjaframework/ninja#332]
I'm trying to do something really simple here, bind a "select multiple" field into a POJO.
As this is such a basic feature, I can't find out if it is not supported (can't find this info anywhere) or I'm doing something wrong.

This is basically what I'm doing

``` html
<select name="clients" id="clients" multiple="multiple">
    <option value="1">Something</option>
    <option value="2">Something else</option>
</select>
```

And in my controller I do this

``` java
public Result postIndex(@JSR303Validation CreateEventDto dto, Validation validation)
{
}
```

The CreateEventDto has a `clients` property which is declared as `long[]` (I also tried with `List<long>` with no luck).

Now, I simply need to get all selected clients in the form, but it does not bind to the right field in `CreateEventDto`. (`long[] clients` is always null).

If I try to get the values via something like `@Params("clients") long[] selectedClients` it **does** work.

The question is, is this supposed to work? 

I tried looking into the code and saw that body parser for post data relies on this [SwissKnife.java](https://github.com/ninjaframework/ninja/blob/develop/ninja-core/src/main/java/ninja/utils/SwissKnife.java#L177) which seems to support only primitive types, but I don't know if I'm looking at the right place.

**Comment by raphaelbauer** [comment]
I think that's not implemented yet. Relevant code is in class BodyParserEnginePost and the line

```
Object convertedValue = SwissKnife.convert(value, field.getType());
```

Would be great if you could find some time to contribute the feature!

**Comment by gabrielhora** [comment]
Thanks Raphael.

I just created a pull request for this, I think it gets the job done well.
Can you review and tell me what you think.

**Comment by raphaelbauer** [comment]
Hey @gabrielhora , I just merged your nice contribution. Please verify that everything is okay and close the issue afterwards. Thanks!

**Comment by gabrielhora** [comment]
Great, thank you @raphaelbauer !
