### ISSUE TITLE
Routes does not work

### ISSUE THREAD

**Issue by koujun2012** [ninjaframework/ninja#358]
if you configure a route /admin,and the path /admin/ does not work.
but normally /admin and /admin/ is same.

**Comment by bazi** [comment]
Ninja determines routes by regular expressions, so to match `/admin` and `/admin/` you can define your route pattern like `route("/admin/?")`. Important part in this regular expression is the _question mark_ after _slash_ which says that there may or may not be a slash in the end of a path.

**Comment by koujun2012** [comment]
thank you very match.
