### ISSUE TITLE
How to fix warning: Could not load file conf/messages_en.properties

### ISSUE THREAD

**Issue by PerfectCarl** [ninjaframework/ninja#377]
When I create an empty application from the maven template, I got the following warnings: 

```
| Could not load file conf/messages_en.properties (not a bad thing necessarily, but I am returing null)
| Did not find conf/messages_en.properties but it was specified in application.conf. Using default language instead. 
```

Indeed the file is missing and the `application.conf` file mentions `en` being the current language.

How could I fix the warning without duplicating my message strings?

**Comment by raphaelbauer** [comment]
That's kind of a stupid error message... Not sure what to do. Improving the error message is one obvious thing...
As "hot fix" you can simply create an empty messages.properties and put all your messages into messages_en.properties (or vice versa)...

**Comment by PerfectCarl** [comment]
Thanks for the _hot fix_: my OCD feels a little better now that I know that I don't do anything wrong :)
I think I'll soldier on and wait for the fixed message in the next release.
