### ISSUE TITLE
On the question, how should do?

### ISSUE THREAD

**Issue by xiaomi1120** [ninjaframework/ninja#390]
[ERROR] No plugin found for prefix 'ninja' in the current project and in the plu
gin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repo
sitories [local (C:\Users\hanxuemin.m2\repository), nexus-osc (http://maven.osc
hina.net/content/groups/public/)] -> [Help 1]

**Comment by ghost** [comment]
How to resolve this?

**Comment by OnePlusGit** [comment]
Was this resolved? Could you please share the solution
