### ISSUE TITLE
Freemarker Upgrade to 2.3.23

### ISSUE THREAD

**Issue by khmarbaise** [ninjaframework/ninja#402]
It would nice to upgrade the freemarker dependency to 2.3.23.

**Comment by raphaelbauer** [comment]
I totally agree. If you got the time feel free to upgrade the library in ninja's main pom.xml (there is just one location and the upgrade is done) => https://github.com/ninjaframework/ninja/blob/develop/pom.xml. Add your change to the changelog, issue a PR and it will ship with the next release :)

In any case I'll leave the issue open as reminder.

**Comment by khmarbaise** [comment]
Updated the changelog as well. Thanks for the hint. Created appropriate PR...
