### ISSUE TITLE
ObjectMapperProvider can not be replaced with a custom implementation

### ISSUE THREAD

**Issue by omervk** [ninjaframework/ninja#405]
I am using Ninja and am using Scala's case classes as requests and responses. This is easily doable with `jackson-module-scala`. However, when I try to set the following to avoid null values in my responses:

```
objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL)
```

Nothing changes.

I've done a lot of digging to repro this issue and found that:
1. ObjectMapper for Ninja Framework uses the Afterburner module (`jackson-module-afterburner`).
2. Afterburner being registered before the Scala module (`jackson-module-scala`) causes Include.NON_NULL not to be taken into account when serializing options in case classes.
3. Ninja declares its own global ObjectMapper using `ObjectMapperProvider`. This provider can't be replaced, injected, etc.
4. There's no way to remove Afterburner after it has been set on an ObjectMapper.

The workaround to this is to replace the template engine's provider with a custom one that passes a custom object mapper in the `Module`:

```
val customObjectMapper = new ObjectMapper()
customObjectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL)
customObjectMapper.registerModule(DefaultScalaModule)
customObjectMapper.registerModule(new AfterburnerModule)

bind(classOf[TemplateEngineJson]).toProvider(new Provider[TemplateEngineJson] {
    override def get(): TemplateEngineJson =
        new TemplateEngineJson(customObjectMapper)
})
```

I would appreciate seeing a nicer implementation (such as being able to provide my own `ObjectMapperProvider`.

**Comment by jjlauer** [comment]
Have you tried a Module to configure the global object mapper at runtime? Here's a sample of one.

``` java
@Singleton
public class JacksonModule {

    @Inject 
    ObjectMapper objectMapper;

    @Start(order = 90)
    public void configureObjectMapper() {
        // adding Joda Time parsing and rendering support to Jackson
        objectMapper.registerModule(new JodaModule());
        objectMapper.enable(SerializationFeature.INDENT_OUTPUT);
        objectMapper.setPropertyNamingStrategy(PropertyNamingStrategy.CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES);
        objectMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
        // include non-nulls?
        //objectMapper.getSerializationConfig().withSerializationInclusion(JsonInclude.Include.NON_EMPTY);
        objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);

        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        df.setTimeZone(TimeZone.getTimeZone("UTC"));
        objectMapper.setDateFormat(df);

        objectMapper.registerModule(module);
    }

}
```

You then schedule this to run at application startup in conf/Module.java

```
package conf;

import com.google.inject.AbstractModule;
import com.google.inject.Singleton;

@Singleton
public class Module extends AbstractModule {

    @Override
    protected void configure() {
        bind(JacksonModule.class);
    }

}
```

Or does the interaction with the Scala module still cause an issue?

**Comment by omervk** [comment]
This is too late in the game. The injected ObjectMapper is already "corrupted" by the Afterburner module.

**Comment by jjlauer** [comment]
Just dug around the code a bit.  Looks like a Provider is already setting up the ObjectMapper.

https://github.com/ninjaframework/ninja/blob/0d690fd19f307e8b7555ad569238fb26b48a2da8/ninja-core/src/main/java/ninja/Configuration.java

```
bind(ObjectMapper.class).toProvider(ObjectMapperProvider.class).in(Singleton.class);
```

I believe you can write your own Provider<T>, bind it on conf/Module.java, and that'll be the provider used everywhere.  If that works, it probably would be good to add to documentation as an alternative way of configuring the object mapper.

**Comment by omervk** [comment]
My point number 3 addresses exactly that. You can't replace the provider that's set up in Configuration.java since Guice will throw an exception because it has multiple providers for the same type.

**Comment by raphaelbauer** [comment]
One way replace the explicit binding with a @ProvidedBy(ObjectMapperProvider.class) annotation.
that way any bind(...).to(...) in your own Module.java can override the default binding... 

A patch would be very welcome!

**Comment by omervk** [comment]
Honestly I'm not sure how to go about this or I would have submitted a patch already...

**Comment by raphaelbauer** [comment]
ok.. here's how I'd do it:

1) Create an interface NinjaObjectMapper which has one method called getObjectMaper and returns an ObjectMapper.
2) Then write a NinjaObjecMapperProvider which implements guice's Provider<NinjaObjectMapper> and has a get() method which returns the NinjaObjectMapper. In that provider we'll add the "default" configuration of the objectmapper as it is now.
3) Annotate the NinjaObjectMapper interface with @ ProvidedBy(NinjaObjecMapperProvider.class)
4) Replace all old stuff like ObjectMapperProvider, and make sure you inject a NinjaObjectMapper into the templates. Then you can call get() on NinjaObjectMapper and get the ObjectMapper for the templates.

If you want to provide your own configuration you can now create your own class that implements NinjaObjecMapperProvider and provide an explicit binding of your provider to NinjaObjecMapperProvider.class. That's how I'd do it (@jjlauer agreed?)....

That should solve everything...
The same should be done for the XmlMapper as well to keep things uniform....

As I wrote above - a PR would be very welcome, they usually get merged and you can see your improvement in the next release!

Let us know if we can help further :)

**Comment by amit2103** [comment]
@raphaelbauer if no one is working on this can I contribute a pull Request?

**Comment by jjlauer** [comment]
Hey, I was needing to override something else the other day, and Guice 4.0
introduced an OptionalBinder.  Perhaps we should consider something like
that vs. the @ProvidedBy concept.

https://google.github.io/guice/api-docs/4.0/javadoc/com/google/inject/multibindings/OptionalBinder.html

**Comment by raphaelbauer** [comment]
Cool @jjlauer - I did not know about the OptionalBinder feature. But that is imho _exactly_ what we want.

@amit2103 would be great if you want to contribute :) Guidelines are here: http://www.ninjaframework.org/developer/getting_started.html

If you hit any roadblocks - let us know - we are here to help!

**Comment by amit2103** [comment]
@raphaelbauer Thanks.
I will get started. However I want to know one thing, should I implement this using OptionalBinder? 
I am not very fluent in Guice or ninja so I might need help...In case I need help I will post here ?

**Comment by raphaelbauer** [comment]
Sure!

With multibindings it should be supersimple...
Steps I see:
1) Add to main pom.xml:

```
    <dependency>
        <groupId>com.google.inject.extensions</groupId>
        <artifactId>guice-multibindings</artifactId>
        <version>${guice.version}</version>
    </dependency>
```

2) Add to nemo-core/pom.xml:

```
    <dependency>
        <groupId>com.google.inject.extensions</groupId>
        <artifactId>guice-multibindings</artifactId>
    </dependency>
```

3) Replace

```
    bind(ObjectMapper.class).toProvider(ObjectMapperProvider.class).in(Singleton.class);
```

with

```
    OptionalBinder.newOptionalBinder(binder(), ObjectMapper.class)
      .setDefault().toProvider(ObjectMapperProvider.class).in(Singleton.class);
```
- same for the XmlMapperProvider to keep things uniform

That's the coding part. Then we ofc need some documentation how to replace the default binding, but that should also be straight forward :)

**Comment by amit2103** [comment]
@raphaelbauer Thanks.
I will get started.

**Comment by omervk** [comment]
I upgraded to Ninja 5.4 and it took me a while to figure things out but was finally able to!
To reiterate, I needed to replace the `ObjectMapper` with my own implementation.

I'll attach my code for future reference for anyone looking for it.

This is now my custom module (including the change from extending `Module` to `FrameworkModule`):

``` scala
@Singleton
class Module(private val ninjaProperties: NinjaProperties) extends FrameworkModule {
    protected def configure(): Unit = {
        install(new NinjaClassicModule(this.ninjaProperties))

        OptionalBinder.newOptionalBinder(binder, classOf[ObjectMapper])
            .setBinding()
            .toProvider(classOf[ObjectMapperProvider])
            .in(classOf[Singleton])
    }
}
```

and the `ObjectMapperProvider` class:

``` scala
object ObjectMapperProvider {
    private val objectMapper = new ObjectMapper()
        .setSerializationInclusion(JsonInclude.Include.NON_NULL)
        .registerModule(DefaultScalaModule)
        .registerModule(new AfterburnerModule)
}

final class ObjectMapperProvider extends Provider[ObjectMapper] {
    override def get() = ObjectMapperProvider.objectMapper
}
```

This works wonderfully, thank you very much for your help! :+1: 

(apologies for this being Scala code. If anything's not understood, I'll be happy to explain)

**Comment by omervk** [comment]
FYI with the release of `jackson-module-scala` 2.7.4, the issue has been resolved, see: https://github.com/FasterXML/jackson-module-scala/issues/226#issuecomment-223813873

**Comment by raphaelbauer** [comment]
Good to know! 👍
