### ISSUE TITLE
Support Hazelcast for Distributed Cache

### ISSUE THREAD

**Issue by amit2103** [ninjaframework/ninja#410]
Currently ninja supports EHCache and Memcache. For a distributed cache Hazelcast or Apache Ignite can be considered, because they have better Java support than Memcache, and also provide a richer functionality than memcache. Any client who will need to use Ignite or Hazelcast for his/her functionality will perhaps be happier if Ninja supports it out of the box as cache layer. 

I can submit a pull request if everyone thinks this is desirable. Any tips (from Ninja side ) to integrate is welcome too. I know Hazelcast well enough.

**Comment by raphaelbauer** [comment]
Ninja is a community project. If you need it - create a Ninja module for it. There are no restrictions or something... :)

The first step is to look how the current cache api's are made (EhCache, Memcached). Then I'd create a Ninja module that implements Hazelcast in a separate github repository. Then people can begin to use it - and then we can decide to move the external module into Ninja's main repo...

That's the approach roughly :) As usual - if you got questions let us know... You can always ask on the mailing list for feedback about potential new modules!

**Comment by amit2103** [comment]
@raphaelbauer Thanks for the response. I will create a module then. Now I am a bit confused about one thing. Should I create a module like ninja-ebeans as ,y repository and then submit it?
