### ISSUE TITLE
Add support for Websocket in Ninja

### ISSUE THREAD

**Issue by amit2103** [ninjaframework/ninja#414]
Ninja should  have web socket support. Found this discussed in the forums in https://groups.google.com/forum/#!topic/ninja-framework/8HgsnRW1Ar4.

It will be cool to integrate Atmosphere in Ninja or even create a new interface. I can work on this however will like someone to provide guidelines. My approach will be to check Play 1 websocket support and try to find how far it is practical to develop that in Ninja.

**Comment by amit2103** [comment]
@raphaelbauer  @jjlauer and others...do you think this will be a usefull addition.

**Comment by raphaelbauer** [comment]
Hey @amit2103 - 
that's of course very useful. Especially (and maybe only) if you got a use-case for it... Api design for websockets should not be too hard, but on the other hand it needs some discussion... I'd first look at other popular frameworks (Play1, Play2, Rails, Atmosphere, Servlet spec) and how they do it, pick the and improve best one and adapt it to Ninja so that we can discuss real stuff...
Hope that helps :)

**Comment by danielsawan** [comment]
Every addition to Ninja is welcome.
I personally wanted to use WebSocket in my under dev ninja app and when i saw that there was nothing like that, I made a simple ajax polling :/

Raphael is right, the first thing to do is to look how most popular Web Framework approach this problem. Then make a "mix" of their best ideas and look how it is possible to integrate those, following the Ninja "philosophy".

**Comment by amit2103** [comment]
Hi All..I think we all can agree that if we are building real time web apps, then Websockets or Server Sent events are both great to have features...In most cases they are not only nice to have but almost must have...Polling the server is an useful workaround but it often creates unnecessary traffic.

I have checked most APi's and I feel we should debate amongst atmosphere or the Play 1 APi. Integrating ATmosphere is great, and useful, but it will be best to also  Play 1's APi along with Servlet. 

I will try to propose an API.

**Comment by mustafaakin** [comment]
Any plans for this?

**Comment by davidgiga1993** [comment]
Any update on this?

**Comment by jjlauer** [comment]
I spent some time awhile back mapping out what a WebSocket api could look
like.  Here's the branch I had started.  It is **very** rough and doesn't
really work.  But it could be a starting point if someone in the Ninja
community wanted to integrate the feature.

https://github.com/fizzed/ninja/tree/feature_websocket

I initially thought that JSR356 as a standard meant getting websocket
support in servlet containers & Ninja would be an easy effort.  The problem
is that JSR356 is somewhat poorly designed, especially with letting you
control the upgrade/handshake process.  I also wanted to let non-servlet
containers such as 'ninja-undertow` https://github.com/fizzed/ninja-undertow
be able to supply WebSockets to ninja w/o servlets.

Here's what I brainstormed for an api.  When setting up your routes, it
would look like this:

public class Routes implements ApplicationRoutes {
    @Override
    public void init(Router router) {
        router.GET().route("/").with(ApplicationController.class, "index");
        router.WS().route("/ws").with(ApplicationController.class,
"websocket");
    }
}

Then in `application.websocket()` you would be able to get any parameters
injected via guice just like any other controller method for the initial
handshake.  Then you would have filters run, reject the handshake, etc.  I
think we'd need to have a special WebSocketResult returned that is the
underlying connection handler if its connected.  Anything other than a
WebSocketResult would mean the handshake should be rejected/fallback to
HTTP.

I got `ninja-standalone` to enable websockets via Jetty, and the route
itself actually is added, but that's as far as I got.  I had to move onto
other projects for the time being.  But if anyone wanted to continue the
effort in the meantime, I'd be happy to help map it out.

-Joe

**Comment by MTyson** [comment]
Darn, needing this one.

**Comment by iamcmnut** [comment]
I want to help you to implement Ninja's native WebSocket.
Could you guide me please?

**Comment by raphaelbauer** [comment]
Closing this - discussion now at: https://github.com/ninjaframework/ninja/issues/545
