### ISSUE TITLE
Listing items using FreeMarker

### ISSUE THREAD

**Issue by ghost** [ninjaframework/ninja#437]
From what I have seen outside of Ninja, the system for rendering a list is as follows:

Java:

```
        Balance balance = new Balance();
        balance.amount = 10L;
        balance.name = "TEST";

        List<Balance> balances = Arrays.asList(balance);


        Result result = Results.html().render("balances", balance);

```

FreeMarker:

```
                    <#list balances as i>
                        <div class="col s1">
                            <div class="bsquare">
                                <div class="head">
                                    ${i.name}
                                </div>
                                <div class="body">
                                    ${i.amount}
                                </div>
                            </div>
                        </div>
                    </#list>
```

However, for some reason in Ninja this creates an error (when rendering, not on compile) of:

For "#list" list source: Expected a sequence or collection, but this has evaluated to an extended_hash+string (models.Balance wrapped into f.e.b.StringModel):
==> balances  [in template "views/ApplicationController/account.ftl.html" at line 13, column 28]

With line 28 being 'list balances as i'

What would be the correct way to do this in Ninja?

**Comment by raphaelbauer** [comment]
On Wed, Dec 23, 2015 at 5:14 AM, William Dunne notifications@github.com
wrote:

> Result result = Results.html().render("balances", balance);

Why is that balance? (and not balances?).
Cheers,
Raphael

**Comment by ghost** [comment]
I've removed coffee from my diet recently, thanks for the help

**Comment by raphaelbauer** [comment]
No worries! I recently switched from coffee to black tea. Seems to do the
job...

**Comment by ghost** [comment]
Might have to give that a try, has less caffeine so might be okay.

**Comment by jjlauer** [comment]
Not to push my own project, but your "oversight" is pretty common and is
something Rocker templates catch during the compilation phase.  Feel free
to check them out at some point.

https://github.com/fizzed/ninja-rocker
https://github.com/fizzed/rocker
https://github.com/fizzed/rocker/blob/master/docs/SYNTAX.md

-Joe
