### ISSUE TITLE
mvn site error

### ISSUE THREAD

**Issue by orangeyts** [ninjaframework/ninja#440]
1 git clone ...
2 cd ninja-core 
3 mvn site

1 error
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.492s
[INFO] Finished at: Thu Jan 07 22:42:36 CST 2016
[INFO] Final Memory: 36M/375M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project ninja-core:
 Error rendering Maven report:
[ERROR] Exit code: 1 - javadoc: error - invalid flag: -Xdoclint:none
[ERROR]
[ERROR] Command line was: "C:\Program Files\Java\jdk1.7.0_79\jre..\bin\javadoc.exe" @options @packages
[ERROR]
[ERROR] Refer to the generated Javadoc files in 'E:\dev\git\ninja\ninja-core\target\site\apidocs' dir.
[ERROR] -> [Help 1]

ENV:

Apache Maven 3.1.1 (0728685237757ffbf44136acec0402957f723d9a; 2013-09-17 23:22:22+0800)
Maven home: E:\dev\interview\apache-maven-3.1.1
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.7.0_79\jre
Default locale: en_US, platform encoding: GBK
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"

**Comment by raphaelbauer** [comment]
You have to use Java 1.8 to create the site...

**Comment by orangeyts** [comment]
thanks, it works,

[INFO] ----------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ----------------------------------------------
[INFO] Total time: 39.944s
[INFO] Finished at: Thu Jan 07 23:06:12 CST 2016
[INFO] Final Memory: 32M/88M
[INFO] ----------------------------------------------

Is that mean ninjaframework need min jdk version is 1.7 ?

**Comment by raphaelbauer** [comment]
Nope. Ninja applications need at least JDK 1.7 (you can use 1.8 of course as well).

**Comment by raphaelbauer** [comment]
please close the issue when you think it's resolved. Thanks!
