### ISSUE TITLE
Missing 'mvn package' step in JPA Documentation

### ISSUE THREAD

**Issue by ghost** [ninjaframework/ninja#444]
http://www.ninjaframework.org/documentation/working_with_relational_dbs/jpa.html

The QUICKSTART section misses the 'mvn package' step, so it should be

`mvn package ninja:run`

or

```
mvn package
mvn ninja:run
```

**Comment by raphaelbauer** [comment]
Nice catch! As written on your other issue - a PR would be really appreciated :) Thanks!
