### ISSUE TITLE
Simplify Configuration within the JPA Documentation

### ISSUE THREAD

**Issue by ghost** [ninjaframework/ninja#445]
http://www.ninjaframework.org/documentation/working_with_relational_dbs/jpa.html

The `Configuration` section mentions the need to configure the database.

But: The blog archetype uses an in-memory db by default (which is very nice so).

So, the minimal change for the documentation would be to add to the `Quickstart` section:

```
the application uses an in-memory db, so you don't need to configure a db. If you like to change to another db, like Postgresql orMySQL , see the `Configuration` section.
```

(Ideally, the `Configuration` section would be moved to the end of the document, thus the `Models` section comes first)

**Comment by raphaelbauer** [comment]
That sounds very reasonable. You can create a PR with your changes. The relevant website files are located at ninja-core/src/main/site/... Looking forward to your PR!
