### ISSUE TITLE
Customizing Default File Locations

### ISSUE THREAD

**Issue by ghost** [ninjaframework/ninja#456]
I have taken a look at the jpa-blog created from the archetype.

The code is placed (as usual within MVC frameworks) within different locations. As an example, code relevant to the `Article` is placed within: models, view, controllers and dao.

Assuming this **must** requirement from a client:
- _Code subjecting a persistent class *_must*\* be available within one location.*

Can this be achieved?

In the given example, can I configure (or via class override) the framework to look for the code within one folder, e.g. `src/main/java/entities/article` tor the Article Entity? The folder would contain:
- Article.java
- ArticleDao.java
- ArticleController.java
- ArticleDto.java
- ArticlesDto.java
- articleNew.ftl.html
- articleShow.ftl.html

(Please do not discuss the requirement, this is mainly to verify if `Ninja` is flexible enough to fulfill the given requirement, and to see the implementation technique)

**Comment by raphaelbauer** [comment]
For Java classes that's possible. ftl.html files are retrieved by convention. They have to live in the view subfolder. But even there you can specify  a location via Results.ok().template(...). Is that what you meant?

**Comment by lazaridis-com** [comment]
I could alter the source-code (its open), but the question is, if Ninja provides an alternative, easier method to configure the location of the ftl.html files (e.g. via configuration, subclassing & override or any other means).
