### ISSUE TITLE
Ending bar '/' shouldn't be ignored in routes?

### ISSUE THREAD

**Issue by yuripourre** [ninjaframework/ninja#479]
I don't know if it has a purpose but these routes shouldn't be the same?

``` Java
router.GET().route("/path").with(ApplicationController.class, "mypath");
router.GET().route("/path/").with(ApplicationController.class, "mypath");
```

Sometimes I forget to put the ending bar in my views so I duplicated all the routes with this ending bar.

**Comment by raphaelbauer** [comment]
Whether a route has a "/" at the end or not makes a difference. However, you can use a regex to tell Ninja that your route accepts both:

```
router.GET().route("/path/?").with(ApplicationController.class, "mypath");
```

**Comment by yuripourre** [comment]
Good tip, thanks

**Comment by raphaelbauer** [comment]
Houskeeping here. Please re-open the issue if you think it is still valid.
