### ISSUE TITLE
@UnitOfWork inside of @Transactional breaks

### ISSUE THREAD

**Issue by D3v01dZA** [ninjaframework/ninja#481]
When using an method annotated with UnitOfWork within a method that is annotated with Transactional the following exception will always occur:

`java.lang.IllegalStateException: Work already begun on this thread. Looks like you have called UnitOfWork.begin() twice without a balancing call to end() in between. at com.google.common.base.Preconditions.checkState(Preconditions.java:173) ~[guava-18.0.jar:na]
    at com.google.inject.persist.jpa.JpaPersistService.begin(JpaPersistService.java:73) ~[guice-persist-4.0.jar:na]`

This seems to be caused because in ninja.jpa.UnitOfWorkInterceptor the status of the UnitOfWork is never checked (the method is also not available on the UnitOfWork interface), however in com.google.inject.persist.jpa.JpaLocalTxnInterceptor it is.

The reason that I didn't submit a pull request is that I am not sure what the desired result is (this happened by accident) because if you were to allow the unit of work to continue it would actually be wrapped in the transaction from the stack before it (not so sure about this, but I thank I am right).

The opposite version of this (UnitOfWork -> Transactional) will work, and should function properly from what I can see (transactional operations will will in the transactional method while not in the unit of work).

**Comment by linhdang** [comment]
+1

**Comment by jlannoy** [comment]
Problem still waiting a Guice persist release. See recent issue : #618

**Comment by jaiabyeti** [comment]
I am using Ninja Version 4.0.4, and this is still breaking for me. Has there been any update on this? #618 does not seem to provide much on this.
