### ISSUE TITLE
How do I configure the package in which my views and controllers are stored?

### ISSUE THREAD

**Issue by JesseTG** [ninjaframework/ninja#483]
I added the line `application.modules.package=www.purple.mixxy` to `conf/application.conf`, and then moved all views to `www.purple.mixxy.views.WhateverPackageHierarchyExistedBefore`.  However, one of the unit tests in the Google App Engine archetype fails (`ApiControllerTest`, line 129).  Is this a bug, or am I missing something?

**Comment by jjlauer** [comment]
Can you copy and paste the entire unit test failure message?

**Comment by JesseTG** [comment]
No, actually, because I seem to have fixed it, I think.

It looks like nothing's actually broken, but the tests are looking for 
the wrong thing; I changed `response.contains("Error. Forbidden.")` and 
similar to just `response.contains("forbidden")`.

I have no idea whether or not that was a good idea, because I'm running 
on fumes right now and am extremely hungry and tired.

What I don't get is what changing the package had to do with it...

**Comment by raphaelbauer** [comment]
Houskeeping here. Please re-open the issue if you think it is still valid.
