### ISSUE TITLE
Jetty configuration : java.lang.IllegalStateException: Form too large: 239268 > 200000

### ISSUE THREAD

**Issue by danielsawan** [ninjaframework/ninja#484]
Hi there !

I have a little problem with posting a big text field form to my controller and get this error

`java.lang.IllegalStateException: Form too large: 239268 > 200000
        at org.eclipse.jetty.server.Request.extractFormParameters(Request.java:364)
        at org.eclipse.jetty.server.Request.extractContentParameters(Request.java:302)
        at org.eclipse.jetty.server.Request.extractParameters(Request.java:256)
        at org.eclipse.jetty.server.Request.getParameter(Request.java:825)
        at javax.servlet.ServletRequestWrapper.getParameter(ServletRequestWrapper.java:194)`

So i searched then how to configure jetty params and found 

> ninja.jetty.configuration allows you to supply a comma-delimited list of jetty.xml configuration files to configure the server. Anything Jetty can do is now available. Please note that if this property is supplied then the host/port property is skipped and you’ll need to configure that in the jetty.xml configuration file. (eg -Dninja.jetty.configuration=jetty.xml,jetty-ssl.xml) Please refer to Jetty distribution for example config files. For each jetty configuration file the local filesystem is searched first, followed by the classpath, and if multiple files are included then each one is applied in order.

So i created a new file "jetty.xml" at the src/main/java near "logback.xml" containing

`<Call name="setAttribute">
    <Arg>org.eclipse.jetty.server.Request.maxFormContentSize</Arg>
    <Arg><Property name="jetty.maxFormContentSize" default="1000000"/></Arg>
  </Call>
`

And finally run my app in dev mode with 

`mvn3 ninja:run -Dninja.jetty.configuration=jetty.xml`

But the bug still here when i make the post request and i feel like the configuration in jetty.xml is just ignored. I know i made something wrong but i don't know where.

Thanks for your help guys !

**Comment by jjlauer** [comment]
Based on this stackoverflow http://stackoverflow.com/questions/3861455/form-too-large-exception it looks like this can be a system property.  Does this work?

mvn ninja:run -Dninja.jvmArgs="-Dorg.mortbay.jetty.Request.maxFormContentSize=100000"

The other workaround would be to use ninja-undertow.  Undertow doesn't have an entity limit by default. https://github.com/fizzed/ninja-undertow

**Comment by danielsawan** [comment]
This right arguments seems to be

`-Dorg.eclipse.jetty.server.Request.maxFormContentSize=5000000`

te mortbay thing doesn't work.

This work perfectly.

`mvn ninja:run -Dninja.jvmArgs="-Dorg.eclipse.jetty.server.Request.maxFormContentSize=5000000"`

I don't know anything about undertow only that it use non-blocking API’s and i feel like i have to modify many lines in my webapp in order to use non-blocking code "style".

I suppose to put this argument on prod i have to do something like 

`java -Dninja.port=9001 -Dorg.eclipse.jetty.server.Request.maxFormContentSize=5000000 -jar myapp.jar`

Is there another way to change Jetty properties programaticly (on ninja start) and not in the command line way ?

Thanks for your help !

**Comment by jjlauer** [comment]
ninja-undertow is a drop-in replacement for ninja-jetty -- you don't change your app code.  You just change your maven pom.xml a bit to use it.

You can programmatically set System properties in Java, but that probably needs to happen before Jetty gets loaded.  I'd say setting it on the command-line like you're doing is frankly the easiest.

**Comment by danielsawan** [comment]
Ok thanks for your help @jjlauer :)
