### ISSUE TITLE
Risky error information in prod mod

### ISSUE THREAD

**Issue by danielsawan** [ninjaframework/ninja#494]
Hi there,

I have an nginx serveur in front of my Ninja app and when i receive some DDOS i noticed that there is some sensible information that are shown : http://puu.sh/o4Lug/7b62ebb3a0.png

I have no controle of that and i think we should be able to configure a template for all non ninja error.
The "hacker" here have the information that i am using JAVA and that i have some problem to connect to my database :-1:

**Comment by raphaelbauer** [comment]
How do you connect to your db - and how is it configured?

**Comment by danielsawan** [comment]
The database is on another server then the Ninja APP.
I am connecting to the database using the "normal" way described in Ninja docs.
The only things is that i am using MySQL compression to compress the trafic between my Ninja App and my MySQL database.

**Comment by raphaelbauer** [comment]
That seems to happen when the error occurs outside of what Ninja can control.

There are two things you can do:
1) Add error-pages to web.xml and define an url that should be used to handle your error (http://www.eclipse.org/jetty/documentation/current/custom-error-pages.html).
2) Add a custom error handler to Jetty's startup, so we can handle those deep errors with Ninja... (https://virgo47.wordpress.com/2015/02/07/jetty-hardening/).

1) should be easy for you to do immediately. 2) Is something we should think about adding to Ninja's Jetty implementation.

**Comment by danielsawan** [comment]
Thanks for your help i will have a look.

**Comment by raphaelbauer** [comment]
Hey @danielsawan - can you check whether https://github.com/ninjaframework/ninja/pull/495 fixes your problem? Thanks!

**Comment by danielsawan** [comment]
I answer on the pr.

**Comment by raphaelbauer** [comment]
Houskeeping here. Please re-open the issue if you think it is still valid.
