### ISSUE TITLE
Regex at beginning of a Route's path fails

### ISSUE THREAD

**Issue by JesseTG** [ninjaframework/ninja#497]
I have a `Route` of the form `(/users)?/{user}/?`.  That is, I want a user's page to be accessible at either `/users/name` like Reddit, or `/name` like GitHub.  And I don't want the presence of a trailing slash to matter.

However, this gets me a long-ass stack trace when I try to access that page.  The top of it looks like this:

```
java.lang.IndexOutOfBoundsException: index (1) must be less than size (1)
    at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:310)
    at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:292)
    at com.google.common.collect.SingletonImmutableList.get(SingletonImmutableList.java:45)
    at ninja.Route.getPathParametersEncoded(Route.java:128)
        ...
```

This problem does not occur if I change the route to `/users/{user}/?`.

**Comment by bazi** [comment]
I found that using capturing groups in routes causes such issues. I proposed a fix in PR #501.
As a workaround you can use `(?:/users)?/{user}/?` until the fix is applied.

**Comment by JesseTG** [comment]
That worked, thanks!  Even if you didn't have a proposed fix, it's not _that_ big of a deal since I don't need `(?:/users)` to capture.

**Comment by JesseTG** [comment]
Fixed by #501

**Comment by raphaelbauer** [comment]
:+1:

**Comment by flniu** [comment]
Thanks! Solved my problem.
