### ISSUE TITLE
dose ninja support modular route?

### ISSUE THREAD

**Issue by ghost** [ninjaframework/ninja#499]
I want to split a web project to some module, every module have it's own route, controllers, db etc. then a small team can focus on dev this module. finally, a root module can integrate all module to build the whole web application.

**Comment by raphaelbauer** [comment]
module like "Maven module"? Routes.java is just a plain java file. So you can of course have a root routes file that integrates all subRoutes.java files...

**Comment by askfor** [comment]
not just route, but also models and controllers and views.

the project structure will look like this:

/conf/
/module1/router.java
/module1/models/
/module1/controllers/
/module1/views/

/module2/router.java
/module2/models/
/module2/controllers/
/module2/views/

**Comment by askfor** [comment]
similar to Django's app

**Comment by ghost** [comment]
@askfor That's exactly what I want.

**Comment by jjlauer** [comment]
Ninja today could support everything I think you're looking for, except one feature which I'll comment on below.
- conf/Routes.java would simply use Java code to include module1/router.java and module2/router.java
- module1/models/ and module2/models/ -- nothing special is really done with models so I'm not sure why you can't put them in packages today.  We do it in our apps all the time.
- module1/controllers/ and module2/controllers -- same as models -- you can put these in these packages now and your router.java would pull them in which in turn would be pulled in with your conf/Routes.java class
- module1/views and module2/views -- if you rely on Ninja's automatic template naming, then you'd need to put them in views/module1/ControllerName and views/module2/ControllerName -- OR you can just do what I do in all my apps and specify an exact template name to use -- OR write a utility method which creates your own template name by default and use it as a post-filter.

**Comment by askfor** [comment]
Hiibernate won't generate DDL for models that were not in /models/ as last time I'm tring the project structure listed above.

**Comment by jjlauer** [comment]
Well, we use ebeans and we can supply a comma-delimited list of packages
for it to scan.

Not sure if the hibernate module supports that.  If it does, a PR w/ docs
would be good.  If it doesn't, then that could be a useful feature and
probably not that hard for someone to impl.

**Comment by raphaelbauer** [comment]
Houskeeping here. Please re-open the issue if you think it is still valid.
