### ISSUE TITLE
CommonsMail leaks information

### ISSUE THREAD

**Issue by jfendler** [ninjaframework/ninja#505]
When using Ninja's (default) CommonsMail implementation, the generated message ID exposes not only the use of JavaMail, but also the application being built with Ninja.
An example is:
`1910940974.2.1461346050051.JavaMail.ninja@app.myserver.com`

I couldn't find the ID generation code within Ninja's code, so I assume it's somewhere in the JavaMail project - but I didn't dig any deeper so far.

Just to let you know..

**Comment by rrarrarra** [comment]
The Message-ID in a mail sent with my ninja-framework-app looks like this:
`Message-ID: <1465723642.9.1461506965549.JavaMail.dev@pc>`
so it seems the `ninja` in your `ninja@app.myserver.com` 
comes from somethng like a username of the current OS.

**Comment by jfendler** [comment]
@rranke yes, you are right. It is likely the OS's user name - so no leak on Ninja's side :-)
Still, I'm wondering if we can get rid of the JavaMail part somehow. JavaMail itself allows for a custom Message ID generation function, but it's deep down the rabbit hole, and probably not too easily accessed from within Ninja.
Or do I miss anything? Any ideas on how to change this without too much effort?

**Comment by raphaelbauer** [comment]
Houskeeping here. Please re-open the issue if you think it is still valid.
