### ISSUE TITLE
Documentation: filter and wrapped context

### ISSUE THREAD

**Issue by raphaelbauer** [ninjaframework/ninja#53]
eg makes a "vanityUrl" filter quite simple to implement

for instance

 @Override
    public Result filter(FilterChain filterChain, Context context) {
            return filterChain.next(new WrappedContext(context) {
                @Override
                public String getPathParameter(String key) {
                    if (USER_ID_SESSION_KEY.equals(key)) {
                        return username;
                    } else {
                        return super.getPathParameter(key);
                    }

**Comment by tbroyer** [comment]
Looks like you somehow resolved that one yesterday with the "Request scopes" page; at least partly.

**Comment by raphaelbauer** [comment]
:+1:
