### ISSUE TITLE
Enhance global filters

### ISSUE THREAD

**Issue by raphaelbauer** [ninjaframework/ninja#547]
Complexity: Large 

- Global filters, migrate existing session handling to simply be a default global filter (that can also be removed/replaced if needed).
- Global filters should be truly global, also working for the assets route for instance

**Comment by jjlauer** [comment]
IMO global filter pipeline could simply be created/modified in `conf/Router.java` so everything is one place.  Then once routes are compiled, they are simply included first in order in each chain that's already being generated for each Route.  For example, the global session cookie handling should be a global filter, but it would be helpful to let a user delete it, move it around in the global pipeline.  E.g. with API-only apps you have no need for session handling.

**Comment by raphaelbauer** [comment]
👍 makes a lot of sense

**Comment by raphaelbauer** [comment]
Hey @jjlauer 

I just played around with global filters and came up with 
https://github.com/ninjaframework/ninja/pull/559

Feedback appreciated. It's not yet finished, just wanted to get some feedback... :)

Thanks,

Raphael

**Comment by jlannoy** [comment]
PR #559 merged.
