### ISSUE TITLE
Make JaxyRoutes scan application package

### ISSUE THREAD

**Issue by annonuser** [ninjaframework/ninja#560]
ninja v5.8.0

Is it possible to get JaxyRoutes to respect the application conf's `application.modules.package` property so that we can still use JaxyRoutes on controllers placed there? I think the offending line is [here](https://github.com/ninjaframework/ninja/blob/660f74b9d6a77fc1e39514ff41e512590ec78105/ninja-jaxy-routes/src/main/java/ninja/jaxy/JaxyRoutes.java#L279).

**Comment by jlannoy** [comment]
Fixed in #647
