### ISSUE TITLE
NinjaClassicModule should have scheduler module toggling

### ISSUE THREAD

**Issue by cbxp** [ninjaframework/ninja#561]
Right now NinjaBaseModule forces install(SchedulerSupport.getModule()) and Bootstrap always creates NinjaBaseModule. If there is no way to disable it, please make it configurable through NinjaClassicModule. 

This enables users to run/not run scheduler in needed modes. For example running tests through NinjaTestServer will start schedulers.

**Comment by jjlauer** [comment]
Hey @cbxp -- sounds like a useful optimization.  I'm pretty tight on time these days so if you wanted to take a stab at submitting a PR, we could get this in on the next release.
