### ISSUE TITLE
why maven donot run？？？

### ISSUE THREAD

**Issue by liudianpeng** [ninjaframework/ninja#568]
`$ mvn ninja:run
[INFO] Scanning for projects...

[INFO]
[INFO] --------------------------------------

[INFO] Building cmy 1.0-SNAPSHOT

[INFO] --------------------------------------

[INFO] --------------------------------------

[INFO] BUILD FAILURE

[INFO] --------------------------------------

[INFO] Total time: 0.286 s

[INFO] Finished at: 2017-03-13T16:34:03+08:00

[INFO] Final Memory: 8M/180M

[INFO] -----------

[ERROR] Failed to execute goal org.ninjaframework:ninja-maven-plugin:6.0.0-rc1:run (default-cli) on project cmy: The plugin org.ninjaframework:ninja-maven-plugin:6.0.0-rc1 requires Maven version 3.3.9 ->Help 1]
[ERROR]

[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[ERROR] Re-run Maven using the -X switch to enable full debug logging.

[ERROR]

[ERROR] For more information about the errors and possible solutions, please read the following articles:

[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginIncompatibleException`

**Comment by kubisflo** [comment]
Try `mvn -version`
Does it match the required version of 3.3.9?

> ninja-maven-plugin:6.0.0-rc1 requires Maven version 3.3.9

**Comment by TuringTD** [comment]
@kubisflo thinkyou very much,is ok

**Comment by raphaelbauer** [comment]
Thanks for clearing things up 👍
