### ISSUE TITLE
FlashScope for current request only

### ISSUE THREAD

**Issue by jjlauer** [ninjaframework/ninja#571]
Was thinking about adding a feature to FlashScope where its only valid for the current request, not for the current + next one.

We use FlashScope to present errors to users in many ways (form post, etc.).  However, we do run into the case where we only want to display the flash for the current request -- but unfortunately its included on the next request as well.  We've hacked around that by having a ClearFlashFilter we run, but I'd like to fix it with a simple new feature.  Allow you to mark the FlashScope data as only being valid for the current request.  Not sure of the best method name, but the code would look:

`flash.currentRequestOnly()`

Allows you to still use flash handling in your templates to display errors, but it makes the flashscope only valid for the currently request, not the current + next one.  The implementation would be really simple -- if the property is present, then we'd treat writing the cookie data out as though it was empty.  That would allow templates to still access the data, but since no cookie is present, it wouldn't exist on the next request.

**Comment by raphaelbauer** [comment]
I think the initial idea was to use flash.now(...), which adds flash stuff to the current request, but not to the next one... (It's badly documented...). Would that already help?

**Comment by jlannoy** [comment]
I discover the now() method now ;)

In my projects when I do a success() or error() that is intended for the current request only, I was simply doing a flash.discard() right after...

**Comment by jjlauer** [comment]
Docs recently polished up to include info on now() vs. put().
