### ISSUE TITLE
Ninja v6.2.0 did not hit maven central?

### ISSUE THREAD

**Issue by jjlauer** [ninjaframework/ninja#586]
Hey @raphaelbauer it looks like v6.2.0 never made it into maven central.  Can you take a look?

**Comment by raphaelbauer** [comment]
Thanks for the information... I re-triggered it... should be available asap...

**Comment by raphaelbauer** [comment]
(for whatever reason I just now received the notification from github issues)

**Comment by raphaelbauer** [comment]
Seems to be available now: http://repo1.maven.org/maven2/org/ninjaframework/ninja/6.2.0/

**Comment by jjlauer** [comment]
:+1: Awesome!
