### ISSUE TITLE
Sync ninja artifacts in the central Maven repository

### ISSUE THREAD

**Issue by jbarop** [ninjaframework/ninja#59]
Sync the Ninja release artifacts from https://oss.sonatype.org/content/repositories/releases/org/ninjaframework/ with the central Maven repository.

It seems that the releases are already promoted but you need to inform the Sonatype guys to initially activate the sync to the central repository.

See https://issues.sonatype.org/browse/OSSRH-3946

**Comment by raphaelbauer** [comment]
Thanks for the hint - you are totally right.

I added a comment and hope the sync will be done asap...
https://issues.sonatype.org/browse/OSSRH-3946?focusedCommentId=175394#comment-175394

Cheers,

Raphael

On Thu, Nov 22, 2012 at 3:12 PM, Johannes Barop notifications@github.comwrote:

> Sync the Ninja release artifacts from
> https://oss.sonatype.org/content/repositories/releases/org/ninjaframework/with the central Maven repository.
> 
> It seems that the releases are already promoted but you need to inform the
> Sonatype guys to initially activate the sync to the central repository.
> 
> See https://issues.sonatype.org/browse/OSSRH-3946
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/reyez/ninja/issues/59.

## 

inc: http://ars-machina.raphaelbauer.com
tech: http://ars-codia.raphaelbauer.com
web: http://raphaelbauer.com

**Comment by jbarop** [comment]
Hm, the sync is activated for days and no ninja artifact in central. Could you ask (in the issue) what's going wrong?

**Comment by raphaelbauer** [comment]
On Thu, Nov 29, 2012 at 11:53 AM, Johannes Barop
notifications@github.comwrote:

> Hm, the sync is activated for days and no ninja artifact in central. Could
> you ask (in the issue) what's going wrong?

No idea...  I posted a question :) Thanks for the notification!

https://issues.sonatype.org/browse/OSSRH-3946?focusedCommentId=175818#comment-175818

ra!

**Comment by jbarop** [comment]
yaay @ http://search.maven.org/#search|ga|1|a%3A%22ninja-core%22  :)

**Comment by raphaelbauer** [comment]
great :)

On Thu, Nov 29, 2012 at 9:09 PM, Johannes Barop notifications@github.comwrote:

> yaay @ http://search.maven.org/#search|ga|1|a%3A%22ninja-core%22http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22ninja-core%22:)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/reyez/ninja/issues/59#issuecomment-10864157.

## 

inc: http://ars-machina.raphaelbauer.com
tech: http://ars-codia.raphaelbauer.com
web: http://raphaelbauer.com
