### ISSUE TITLE
Duplicate count for timed metric

### ISSUE THREAD

**Issue by christiangroth** [ninjaframework/ninja#595]
Due to the call of stop() and close() the timer is calculated twice as close() calls stop() internally. If you create a simple @timed annotated controller method you can see that a single request results in count=2 for this timer in corresponding mbean.
  
https://github.com/ninjaframework/ninja/blob/3a9f02bd32a3963f2dd8b0996e951253797a5456/ninja-metrics/src/main/java/ninja/metrics/TimedInterceptor.java#L56-L62

**Comment by raphaelbauer** [comment]
Nice finding! Would you mind creating a PR for that?

**Comment by christiangroth** [comment]
There you go: https://github.com/ninjaframework/ninja/pull/596 :)
