### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by jonathanpopp** [ninjaframework/ninja#606]
Is it possible to return the localized message to the browser when an exception occurs?

Currently, i am just getting:
{"text":"Oops. That's an internal server error and all we know."}

But in the logs i can see
":ninja.exceptions.RenderingException: org.hibernate.exception.GenericJDBCException: could not extract ResultSet"

Can Ninja return the exception message instead of the default Oops message?:
{"text":"org.hibernate.exception.GenericJDBCException: could not extract ResultSet"}

Rest service:

	@POST
	@Path("/deleterightstrand")	
	public Result deleteRightStrand(Context context, DeleteRightsRestrictionStrandCreateObject deleteObject) throws RenderingException {		
		String loginId = "";
		try {						
			... code 
		} catch(ErmValidationException e) {
			getLogger().log(Level.SEVERE,"ErmValidationException exception deleting right strand for user " + loginId,e);
			getLogger().log(Level.SEVERE,"Exception deleting right strand message " + e.getLocalizedMessage());		
			throw new RenderingException(e.getLocalizedMessage());
		} catch(Exception e) {			
			getLogger().log(Level.SEVERE,"Exception deleting right strand for user " + loginId,e);
			getLogger().log(Level.SEVERE,"Exception deleting right strand message " + e.getLocalizedMessage());
			throw new RenderingException(e.getLocalizedMessage());
		}
	}

**Comment by jonathanpopp** [comment]
I think i figured it out, just needed to always return a ninja result:

return Results.status(Status.INTERNAL_SERVER_ERROR.getStatusCode()).text().render(e.getMessage());

**Comment by jlannoy** [comment]
Now error message will also contains your exception localized message, in a "error" parameter, along with the default "text" one. Info will be available trough the [documentation](http://www.ninjaframework.org/documentation/basic_concepts/error_handling.html) once PR #627 is merged and released.
