### ISSUE TITLE
Possibility to set a package prefix

### ISSUE THREAD

**Issue by jbarop** [ninjaframework/ninja#61]
Hi,

I love the convention thing however I'd love to be able to set some sort package prefix where Ninja looks for stuff. For example "src/main/java/assets, src/main/java/conf" could become "src/main/java/$prefix/assets, src/main/$prefix/java/conf".

Why? I love simple project setups. Including as little as possible Maven modules. In my application the GWT client and the backend are in the same module. It works but the it could be structured better by moving the backend code into a sub package which is not yet possible.

What do you think?

**Comment by christiangoudreau** [comment]
Personally I would prefer that the code follow the maven convention, for exemple, assets should be in the resource tree.

**Comment by raphaelbauer** [comment]
@christian:
using a plain maven layout should work out of the box - i did not test it,
but it should make no difference for the classloader of maven if the assets
are in src/main/java/assets or in src/main/resources/assets

@johannes: As far as I can remember the prefix is set by one system wide
constant - making that constant dynamic should be straight forward... but
this has to be tested :)

Cheers,

Raphael

On Thu, Nov 29, 2012 at 1:50 PM, christiangoudreau <notifications@github.com

> wrote:
> 
> Personally I would prefer that the code follow the maven convention, for
> exemple, assets should be in the resource tree.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/reyez/ninja/issues/61#issuecomment-10845941.

## 

inc: http://ars-machina.raphaelbauer.com
tech: http://ars-codia.raphaelbauer.com
web: http://raphaelbauer.com

**Comment by jbarop** [comment]
I have no problem keeping the resources in src/main/ressources - As long they end up in target/classes it should not matter.

I looked into the code and as far I can tell it's not a constant.
https://github.com/reyez/ninja/blob/36ce32d52bca34648eca0f3ec7f30bfc7fdb930b/ninja-core/src/main/java/ninja/NinjaBootup.java#L35
https://github.com/reyez/ninja/blob/36ce32d52bca34648eca0f3ec7f30bfc7fdb930b/ninja-core/src/main/java/ninja/utils/SwissKnife.java#L73
https://github.com/reyez/ninja/blob/36ce32d52bca34648eca0f3ec7f30bfc7fdb930b/ninja-core/src/main/java/ninja/i18n/LangImpl.java#L117
...

If you think this is a nice feature to add, I'll look into this.

**Comment by christiangoudreau** [comment]
It's not a feature :D I'm just madly in love with conventions :P

**Comment by raphaelbauer** [comment]
prefix stuff contributed by community and already happily living in ninja core :)
closing this issue...
raphael
