### ISSUE TITLE
Remove controller-method-strings from conf/Routes and replace it with a DSL complety in Java

### ISSUE THREAD

**Issue by jbarop** [ninjaframework/ninja#64]
Hi,

I did a small hack to use real Java methods in conf.Routes by using Mockito. Dunno if that is an good idea? Works in Jetty.
https://github.com/jbarop/ninja/compare/remove-controller-methods-strings

In further steps I would move the defenition of parameters from the controller to conf.Routes. This way Ninja could have a single central place to configure routes and parameter stuff.

Example of my idea:

```
void init(Router router) {
    router.POST("/person").with(PersonController.class).createPerson(
        router.bodyParameter(Person.class).jsr510().value());

    router.GET("/person/{personId}").with(PersonController.class).getPerson(
        router.pathParameter(String.class, "personId").value());

    router.PUT("/person/{personId}").with(PersonController.class).updatePerson(
        router.pathParameter(String.class, "personId").value(),
        router.bodyParameter(Person.class).value());

    router.DELETE("/person/{personId}").with(PersonController.class).deletePerson(
        router.pathParameter(String.class, "personId").value());

    router.GET("/person").with(PersonController.class).listPersons(
        router.queryParameter(Integer.class, "start").min(0).value(),
        router.queryParameter(Integer.class, "limit").min(0).max(50).value());
}
```

What do you think?

**Comment by raphaelbauer** [comment]
Hi Johannes,

I was thinking about that, too.
The advantages are pretty clear: Type safety. Yea!

But I was wondering if it is a step int he wrong direction. Making things
too complex for somebody writing her first controller.

Neither ruby nor play1 did have type safety in their routes file. Therefore
I went for the "unsafe" but a bit less cluttered option.

But I am not entirely sure about that. I really like the idea... Hmm...

ra!

On Wed, Dec 5, 2012 at 11:41 PM, Johannes Barop notifications@github.comwrote:

> Hi,
> 
> I did a small hack to use real Java methods in conf.Routes by using
> Mockito. Dunno if that is an good idea? Works in Jetty.
> https://github.com/jbarop/ninja/compare/remove-controller-methods-strings
> 
> In further steps I would move the defenition of parameters from the
> controller. This way Ninja could have a single central place to configure
> routes and parameter stuff.
> 
> Example of my idea:
> 
> void init(Router router) {
>     router.POST("/person").with(PersonController.class).createPerson(
>         router.bodyParameter(Person.class).jsr510().value());
> 
> ```
> router.GET("/person/{personId}").with(PersonController.class).getPerson(
>     router.pathParameter(String.class, "personId").value());
> 
> router.PUT("/person/{personId}").with(PersonController.class).updatePerson(
>     router.pathParameter(String.class, "personId").value(),
>     router.bodyParameter(Person.class).value());
> 
> router.DELETE("/person/{personId}").with(PersonController.class).deletePerson(
>     router.pathParameter(String.class, "personId").value());
> 
> router.GET("/person").with(PersonController.class).listPersons(
>     router.queryParameter(Integer.class, "start").min(0).value(),
>     router.queryParameter(Integer.class, "limit").min(0).max(50).value());
> ```
> 
> }
> 
> What do you think?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/reyez/ninja/issues/64.

## 

inc: http://ars-machina.raphaelbauer.com
tech: http://ars-codia.raphaelbauer.com
web: http://raphaelbauer.com

**Comment by jbarop** [comment]
I totally agree that things should be as simple as possible. But not simpler. In particular we'll losing key out-of-the-box advantages of Java such as code completion, compile-time-checking, refactoring and last but not least flexibility.
I think trough Mockito and Guice the concept is well-known to the developers.

To make it much more readable ApplicationRoutes could be an abstract class.

**Comment by raphaelbauer** [comment]
Hi Johannes,

if it is not too urgent I'll have a look in January. As I said - I think it
is a really good idea. But I'd like to think about it a bit first... I hope
that's okay... :)

Raphael

On Tue, Dec 11, 2012 at 3:35 PM, Johannes Barop notifications@github.comwrote:

> I totally agree that things should be as simple as possible. But not
> simpler. In particular we'll losing key out-of-the-box advantages of Java
> such as code completion, compile-time-checking, refactoring and last but
> not least flexibility.
> I think trough Mockito and Guice the concept is well-known to the
> developers.
> 
> To make it much more readable ApplicationRoutes could be an abstract class.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/reyez/ninja/issues/64#issuecomment-11245574.

## 

inc: http://ars-machina.raphaelbauer.com
tech: http://ars-codia.raphaelbauer.com
web: http://raphaelbauer.com

**Comment by jbarop** [comment]
Yea, it's not ready to merge anyways. I'll just wanted to kick of a discussion :)

Maybe I find some time to build a more complete example until January

**Comment by raphaelbauer** [comment]
I think we should wait for Java8. Then it's easy to reference methods like class::method... :)

**Comment by raphaelbauer** [comment]
Hey @jbarop Ninja6 now has full support for Java8 typesafe Class and method references. It's already in master and a beta will be released in January. Closing this ticket therefore. Thanks for your feedback and engagement with Ninja :)

**Comment by jbarop** [comment]
Cool stuff!
