### ISSUE TITLE
Dependency Conflict: duplicate classes "com.codahale.metrics.ScheduledReporter" in different JARs, have different implementations. 

### ISSUE THREAD

**Issue by HelloCoCooo** [ninjaframework/ninja#654]
Hi, in **ninja-6.4.2** (**ninja-metrics-librato** module), duplicate classes with the same fully-qualified name _**com.codahale.metrics.ScheduledReporter**_ are included in two different libraries, i.e., **io.dropwizard.metrics:metrics-core:3.2.6** and **com.codahale.metrics:metrics-core:3.0.1**.

According to _"first declaration wins"_ class loading strategy, only this class in **io.dropwizard.metrics:metrics-core:3.2.6** can be loaded, and that in commons-**com.codahale.metrics:metrics-core:3.0.1** will be shadowed.

By further analyzing, your project expects to invoke methods  _**<com.codahale.metrics.ScheduledReporter: void <init>(MetricRegistry, java.lang.String, MetricFilter, TimeUnit, TimeUnit)>**_  and  _**<com.codahale.metrics.ScheduledReporter: void stop()>**_  in **com.codahale.metrics:metrics-core:3.0.1**. As they have been shadowed, so that these methods defined in **io.dropwizard.metrics:metrics-core:3.2.6** are actually forced to be referenced via the following invocation path:
```
<ninja.metrics.librato.NinjaLibrato: void startService()> D:\testcase\TestProject\ninja-ninja-6.4.1\ninja-metrics-librato\target\classes
<com.librato.metrics.LibratoReporter: void enable(com.librato.metrics.LibratoReporter$Builder,long,java.util.concurrent.TimeUnit)> D:\cEnvironment\repository\com\librato\metrics\metrics-librato\4.0.1.7\metrics-librato-4.0.1.7.jar
<com.librato.metrics.LibratoReporter$Builder: com.librato.metrics.LibratoReporter build()> D:\cEnvironment\repository\com\librato\metrics\metrics-librato\4.0.1.7\metrics-librato-4.0.1.7.jar
<com.librato.metrics.LibratoReporter: void <init>(com.codahale.metrics.MetricRegistry,java.lang.String,com.codahale.metrics.MetricFilter,java.util.concurrent.TimeUnit,java.util.concurrent.TimeUnit,com.librato.metrics.Sanitizer,java.lang.String,long,java.util.concurrent.TimeUnit,com.codahale.metrics.Clock,com.librato.metrics.LibratoReporter$MetricExpansionConfig,com.librato.metrics.HttpPoster,java.lang.String,java.lang.String,java.util.regex.Pattern,boolean,boolean,com.librato.metrics.LibratoReporter$1)> D:\cEnvironment\repository\com\librato\metrics\metrics-librato\4.0.1.7\metrics-librato-4.0.1.7.jar
<com.librato.metrics.LibratoReporter: void <init>(com.codahale.metrics.MetricRegistry,java.lang.String,com.codahale.metrics.MetricFilter,java.util.concurrent.TimeUnit,java.util.concurrent.TimeUnit,com.librato.metrics.Sanitizer,java.lang.String,long,java.util.concurrent.TimeUnit,com.codahale.metrics.Clock,com.librato.metrics.LibratoReporter$MetricExpansionConfig,com.librato.metrics.HttpPoster,java.lang.String,java.lang.String,java.util.regex.Pattern,boolean,boolean)> D:\cEnvironment\repository\com\librato\metrics\metrics-librato\4.0.1.7\metrics-librato-4.0.1.7.jar
<com.codahale.metrics.ScheduledReporter: void <init>(com.codahale.metrics.MetricRegistry,java.lang.String,com.codahale.metrics.MetricFilter,java.util.concurrent.TimeUnit,java.util.concurrent.TimeUnit)>

```

Although both of these two conflicting classes contain the referenced methods (with the same signature), they have different implementations. This issue will not lead to runtime crashes, but it can introduce inconsistent semantic hehavior by changing the control flows and data flows.

**_Workaround solution:_**
The easy way to workaround the problem is **_reversing the declaration order_** of these two libraries in pom file. Then, according to "first declaration wins" class loading strategy, class _**com.codahale.metrics.ScheduledReporter**_ in **com.codahale.metrics:metrics-core:3.0.1** can be loaded (the version that ninja expects to reference by static analysis).
This fix will not affect other libraries or class, except the above duplicate class.

**_Dependency tree:_**
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ ninja-metrics-librato ---
[INFO] org.ninjaframework:ninja-metrics-librato:jar:6.4.2
[INFO] +- org.ninjaframework:ninja-metrics:jar:6.4.2:compile
…..
[INFO] |  |  \- com.google.inject.extensions:guice-multibindings:jar:4.2.0:compile
[INFO] |  |     \- (com.google.inject:guice:jar:4.2.0:compile - omitted for duplicate)
[INFO] |  +- **io.dropwizard.metrics:metrics-core:jar:3.2.6:compile**
[INFO] |  |  \- (org.slf4j:slf4j-api:jar:1.7.22:compile - omitted for conflict with 1.6.6)
[INFO] |  +- io.dropwizard.metrics:metrics-jvm:jar:3.2.6:compile
[INFO] |  |  +- **(io.dropwizard.metrics:metrics-core:jar:3.2.6:compile - omitted for duplicate)**
[INFO] |  |  \- (org.slf4j:slf4j-api:jar:1.7.22:compile - omitted for duplicate)
[INFO] |  \- io.dropwizard.metrics:metrics-logback:jar:3.2.6:compile
[INFO] |     +- **(io.dropwizard.metrics:metrics-core:jar:3.2.6:compile - omitted for duplicate)**
[INFO] |     +- (ch.qos.logback:logback-classic:jar:1.2.3:compile - version managed from 1.1.10; omitted for duplicate)
[INFO] |     \- (org.slf4j:slf4j-api:jar:1.7.22:compile - omitted for duplicate)
[INFO] +- com.librato.metrics:metrics-librato:jar:4.0.1.7:compile
[INFO] |  +- com.librato.metrics:librato-java:jar:1.0.6:compile
[INFO] |  |  +- (com.ning:async-http-client:jar:1.7.4:compile - omitted for duplicate)
[INFO] |  |  +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.7:compile
[INFO] |  |  |  \- org.codehaus.jackson:jackson-core-asl:jar:1.9.7:compile
[INFO] |  |  \- (org.slf4j:slf4j-api:jar:1.6.6:compile - omitted for conflict with 1.7.22)
[INFO] |  +- **com.codahale.metrics:metrics-core:jar:3.0.1:compile**
[INFO] |  |  \- (org.slf4j:slf4j-api:jar:1.7.5:compile - omitted for conflict with 1.7.22)
[INFO] |  +- com.ning:async-http-client:jar:1.7.4:compile
[INFO] |  |  +- io.netty:netty:jar:3.4.1.Final:compile
[INFO] |  |  \- (org.slf4j:slf4j-api:jar:1.6.2:compile - omitted for conflict with 1.7.22)
[INFO] |  \- org.slf4j:slf4j-api:jar:1.6.6:compile

Thanks!
Best regards,
Coco

**Comment by HelloCoCooo** [comment]
Code snippets of **_<com.codahale.metrics.ScheduledReporter: void (MetricRegistry, java.lang.String, MetricFilter, TimeUnit, TimeUnit)>_** and **_<com.codahale.metrics.ScheduledReporter: void stop()>_**  in **_io.dropwizard.metrics:metrics-core:jar:3.2.6 (loaded version)_**:
![111](https://user-images.githubusercontent.com/46306510/55569992-1f359800-5735-11e9-9016-6289baa3a637.png)
![222](https://user-images.githubusercontent.com/46306510/55570002-2492e280-5735-11e9-8fda-283c83519ca0.png)


Code snippets of **_<com.codahale.metrics.ScheduledReporter: void (MetricRegistry, java.lang.String, MetricFilter, TimeUnit, TimeUnit)>_** and **_<com.codahale.metrics.ScheduledReporter: void stop()>_**  in **com.codahale.metrics:metrics-core:jar:3.0.1:compile** (shadowed but expected to invoke method):
![333](https://user-images.githubusercontent.com/46306510/55570010-29579680-5735-11e9-8008-0215d74ce7f6.png)
![444](https://user-images.githubusercontent.com/46306510/55570019-2d83b400-5735-11e9-8d7c-be35b37d3570.png)
![555](https://user-images.githubusercontent.com/46306510/55570030-2f4d7780-5735-11e9-806b-1061aa9d1513.png)
![666](https://user-images.githubusercontent.com/46306510/55570032-31afd180-5735-11e9-845c-0d942428c4de.png)


As a result, these conflicting method included in  **com.codahale.metrics:metrics-core:jar:3.0.1:compile** deals with different cases, which changes the control flows and data flows. So being forced to use these methods in **io.dropwizard.metrics:metrics-core:jar:3.2.6** may lead to inconsisitent semantic behaviors.

**Comment by HelloCoCooo** [comment]
@jlannoy Could please help me check this issue?
May I pull a request to fix it? 
Thanks again.

**Comment by jlannoy** [comment]
Hello @HelloCoCooo 

I looked at it, but I don't agree with your proposed fix. It seems the real problem comes from **ninja-metrics-influxdb** which references an old version of **metrics-influxdb** (not ninja library) which references the old metrics-core version. All other ninja-metrics projects are now referencing the 3.2.6 (ninja-metrics-*). So downgrading the whole stack doesn't seem me the right choice here... The best way would be to upgrade **ninja-metrics-influxdb**.

So my question, as I don't understand it in your request : is there any reason you want to stay on metrics 3.0.1? Or is it more a matter of having a clean and updated stack?

**Comment by HelloCoCooo** [comment]
@jlannoy 
Thanks for your quick reply.
This issue comes from _**ninja-metrics-librato**_, I didn't suggest to upgrade or downgrade any library.
I found that two different libraries (_**io.dropwizard.metrics:metrics-core:3.2.6**_ and _**com.codahale.metrics:metrics-core:3.0.1**_) in this project contain the classes with the same fully-qualified name (**_com.codahale.metrics.ScheduledReporter_**) but have different implementations. Only this class included in the **_first declared library **io.dropwizard.metrics:metrics-core:3.2.6**_** can be loaded.

So that the easy way to solve the problem is **_reversing the declaration order_** of these two libraries in pom file. Then, according to _"first declaration wins"_ class loading strategy, class **com.codahale.metrics.ScheduledReporter** in **com.codahale.metrics:metrics-core:3.0.1** can be loaded (the version that ninja expects to reference by static analysis).

This fix will not affect other libraries or class, except the above duplicate class.


Using the following test case to run on these two versions of methods separately starting from the entry method **_NinjaLibrato.startService()_** in your project, then we can find it return value is changed.
[ninja_test.txt](https://github.com/ninjaframework/ninja/files/3183030/ninja_test.txt)


Please check whether the changes of this variable value will affect your semantic behaviors.

Thanks again.

**Comment by jlannoy** [comment]
_I found that two different libraries (io.dropwizard.metrics:metrics-core:3.2.6 and com.codahale.metrics:metrics-core:3.0.1) in this project_ 

Not exactly, that's what I was explaining you you can't reverse these particular delcarations.

_So that the easy way to solve the problem is reversing the declaration order of these two libraries in pom file._

These two libraries are not referenced in the pom file, but are transitive references. Check your dependency tree, **ninja-metrics-librato** uses
- **ninja-metrics** which references **io.dropwizard.metrics:metrics-core:3.2.6**
- **metrics-librato** which references **com.codahale.metrics:metrics-core:jar:3.0.1**

So if you want to reverse something, it should be these two ;-)
But I personally think it's a bad idea to bet on the _first declaration wins_ fact in a stack like Ninja. (@raphaelbauer ?)

Btw, you don't answer my question : is there any reason you want to explicitly set it to metrics 3.0.1 ? In place of upgrading **metrics-librato** or ignoring **com.codahale.metrics:metrics-core:jar:3.0.1** to use 3.2.6 everywhere.

**Comment by HelloCoCooo** [comment]
I pulled a request #655 following your suggestion.

**Comment by jlannoy** [comment]
Thank you!
