### ISSUE TITLE
XSS in example blog application

### ISSUE THREAD

**Issue by fxb-cocacoding** [ninjaframework/ninja#671]
If you run the example blog application via

`mvn archetype:generate -DarchetypeGroupId=org.ninjaframework -DarchetypeArtifactId=ninja-servlet-jpa-blog-archetype`

then the example application has a persistent cross site scripting vulnerability.
You can reproduce this behavior if you create a new blog entry with

`<script>alert('xss')</script>`

**Comment by raphaelbauer** [comment]
Wonderful finding! Would you mind fixing the archetype?

**Comment by llenrup** [comment]
No HTML is being escaped after update to the latest version of freemarker as it changed various things . See my pull request for a way around this.
