### ISSUE TITLE
Option to disable splash screen

### ISSUE THREAD

**Issue by toyg** [ninjaframework/ninja#674]
It would be cool to have an option to disable the splash screen. Yes it's cool and everything, but it looks a bit unprofessional when you are distributing an app.

Having something like `ninja.splashLogo=false` (with default value being `true`) would be nice to have. If you really don't like the idea, you could leave it undocumented; this way nobody would know it's there, but people wouldn't have to fork the whole repo just to remove that bit.

**Comment by jjlauer** [comment]
Good point on distributing an app based on Ninja.  I'd be okay with a PR
that made it a configurable option to hide it. I'm guessing Raphael would
probably be okay with that too.  To keep with our naming convention
something like ninja.splash.display that defaults to true.  If you wanted
to take it a step further, you could add another option to load a resource
that's an alternative splash logo.

**Comment by toyg** [comment]
PR is in the oven. 
- ninja.splash.display behaving as above
- at startup, ninja looks for a ninja/logo.txt resource to use; if not available, it uses the classic logo. This would reduce "property creep".

I can squash the commits if you want, just wanted to make sure you're ok with the approach, locations etc.

Not sure where or how to add a test for it, any pointer is welcome.
