### ISSUE TITLE
Ninja v6.6.1 not listed on Maven Central

### ISSUE THREAD

**Issue by jowerner** [ninjaframework/ninja#679]
Latest Ninja v6.6.1 (v6.6.0 as well) is not available on Maven Central. Could you please have a look? Thanks!

**Comment by raphaelbauer** [comment]
Thanks for the hint! 6.6.1 should be live asap.
Cheers,
Raphael

**Comment by jowerner** [comment]
Yep, it's there now. Thanks again!

**Comment by raphaelbauer** [comment]
Thank you for reporting!
