### ISSUE TITLE
Compatible with JDK14?

### ISSUE THREAD

**Issue by davidgiga1993** [ninjaframework/ninja#682]
Hello,
I coudn't find an answer to this question but which JDK version is supported by ninja?
My best guess was that some dependency might still require 8 or 11?

**Comment by raphaelbauer** [comment]
It's 11 right now.

**Comment by raphaelbauer** [comment]
We did not test it on newer JDK versions. If you got any feedback let us
know!

I don't see any big obstacles.

Cheers,

Raphael

**Comment by davidgiga1993** [comment]
After some extensive testing I couldn't find any issues so far 👍
