### ISSUE TITLE
@JSR303Validation field validaton

### ISSUE THREAD

**Issue by zoza** [ninjaframework/ninja#69]
hi all
then using @JSR303Validation the "field" is null but in original java bean validation you can get the key from javax.validation.ConstraintViolation.getPropertyPath(). 
also today for this type of validation you use ConstraintViolation and not FieldViolation

i know that you can create custom validator and put on class (not property\method)

i suggest: in ninja.validation.Validators.JSRValidator.validate(Object, String, Validation)

pseudocode:

``` java
for (ConstraintViolation<Object> violation : violations) {
if(violation.getPropertyPath() == null or empty){ // asume class validator
                validation.addGlobalViolation(ninja.validation.ConstraintViolation
                        .create(violation.getMessage()));
}else{
                validation.addFieldViolation(ninja.validation.FieldViolation
                        .create(violation.getMessage(),violation.getPropertyPath(), 
                                violation.getInvalidValue()));
}
}
```

i think every validation error that have field, should be as field FieldViolation, no matter if its JSRValidator or param validator 
and global Violations must be only for class validations

**Comment by raphaelbauer** [comment]
@philipsommer Could you comment on that? You lately added a lot of enhancements to the violation checking and are for sure the right person :)

**Comment by philipsommer** [comment]
Hi All,

you are right, there's still some stuff missing and not quite perfect. I startet to fix this and some more issues on that in branch
https://github.com/reyez/ninja/tree/feature/ErrorObjectsInValidation
It's not ready yet, but if one of you has the time to have a look, would be nice. Please feel free to comment!
Hope to have the time soon to complete my work on that.

regards, Philip

**Comment by raphaelbauer** [comment]
Hi @philipsommer,

I just played around with the validation.
Let's say I got an object called "Contact"

public class Contact {
    @Size(min = 10, max = 20)
    public String name;
}

I should be able to call validation.getFieldConstraintViolation("name") - right? I am only getting "null". But validation.hasViolations seems to work correctly...

Is this a known issue?

Thanks!

Raphael

**Comment by zoza** [comment]
another issue with this kind validator implementation:

story:
in many cases you want to add some values after the object arrived to controller.
like adding creator = current_user or creation time , add some relation , etc...
and for many reasons you must do this on server side.

but in our case its too late.. because we call to .validate before controller code.
the validator obj already has the error.

i suggest (also for back compatible) to add some conf value
<b>JSR303ValidationOnDemand=true\false</b> (false = default) and if true do not call .validate as today
but add  .validate to Validation class and give to developer to call it after hi is done all his stuff

**Comment by raphaelbauer** [comment]
On Thu, Feb 21, 2013 at 11:47 PM, Anatoly notifications@github.com wrote:

> another issue with this kind validator implementation:
> 
> story:
> in many cases you want to add some values after the object arrived to
> controller.
> like adding creator = current_user or creation time , add some relation ,
> etc...
> and for security reasons you must do this on server side.
> 
> but in our case its too late.. because we call to .validate before
> controller code.
> the validator obj already has the error.
> 
> i suggest (also for back compatible) to add some conf value
> _JSR303ValidationOnDemand=true\false_ (false = default) and if true do
> not call .validate as today
> but add .validate to Validation class and give to developer to call it
> after hi done all his defaults
> 
> Hmm. I never had that usecase...

Another idea: We are already injecting a Validation validation object into
the controller. What if this validation method had a ".revalidate" method?
You can then easily revalidate the object on demand if necessary...

Best,

Raphael

>  —
> Reply to this email directly or view it on GitHubhttps://github.com/reyez/ninja/issues/69#issuecomment-13917998.

## 

inc: http://ars-machina.raphaelbauer.com
tech: http://ars-codia.raphaelbauer.com
web: http://raphaelbauer.com

**Comment by zoza** [comment]
That +- what I said, but the difference if to call validate first time by
default or not.
The best way is to choose this with configuration parameter
22.02.2013 12:26 пользователь "reyez" notifications@github.com написал:

**Comment by raphaelbauer** [comment]
Hmm...
what about the following:

If you are using the annotation @JSR303Validation  like so:
public void function(@JSR303Validation Dto dto, Validation validation)
 ...
}
the dto is automatically validated...

other wise you have to call validate yourself - and you can add stuff before everything gets validated...
sketch:
public void function(Dto dto, Validation validation) {

myObject.user = "user";
valididation.validate(myObject);
 ...
}

I am not sure if this is already working that way - but this would exactly do what you need and we do not need a configuration parameter :)

**Comment by zoza** [comment]
yes, its ok for me.

but validation.validate(myObject); will work only as JSR303Validation ??

**Comment by raphaelbauer** [comment]
Closing the issue for now. Feel free to reopen it if its not working that way :)
