### ISSUE TITLE
flash cookie and redirect

### ISSUE THREAD

**Issue by zoza** [ninjaframework/ninja#70]
add line  flashCookie.success("redirect to page %s ", "/"); to redirect action (from demo)

``` java
 public Result redirect(Context context,FlashCookie flashCookie) {
        flashCookie.success("redirect to page %s ", "/");
        // Redirects back to the main page simply call redirect
        return Results.redirect("/");
}
```

and in index.ftl.html

``` html
<#if flash_success??>
        <p class="success">${flash_success}</p>
</#if>
```

open http://localhost:8080/redirect 
redirected to / but flashCookie message is not shown

**Comment by raphaelbauer** [comment]
Hi Anatoly,
thanks for pointing that out! We'll fix that asap :)
ra!

**Comment by raphaelbauer** [comment]
Can you try with the latest develop? Should be fixed by now (with a testcase). The flash cookie had 1970 as timestamp what caused trouble...

https://github.com/reyez/ninja/commit/66f7b8788998c2bd96e8dd02639722a4b24e61be

Thanks for reporting this :)

Raphael

**Comment by zoza** [comment]
yes, in my simple test it works
