### ISSUE TITLE
make assets dir configurable

### ISSUE THREAD

**Issue by asolntsev** [ninjaframework/ninja#712]
Currently assets dir is hardcoded: `src/main/java/assets`. Though, a best practice in Java project is storing such resources in `src/main/resources`. 

I suggest at least to make it configurable.

**Comment by raphaelbauer** [comment]
Same is in #713 - sounds like a good idea and we are really open to PRs :) Let us know if we can help!

**Comment by asolntsev** [comment]
@raphaelbauer yes, I will prepare a PR.
