### ISSUE TITLE
Is it still active? / Looking for maintainers?

### ISSUE THREAD

**Issue by thibaultmeyer** [ninjaframework/ninja#721]
Hello,

Is the framework still maintained? I see a lot of issues that have been open for at least 5 years and are answered/solved but not closed.

are you looking for maintainers, at least to take care of the issues/PR part (ie: apply labels, clean too old issues, assign reviewer...) ?

**Comment by jjlauer** [comment]
Hey @thibaultmeyer -- while development has slowed down, @raphaelbauer and myself still chat frequently and are involved. Yes, we're always looking for help or folks interested in maintenance.

We rely on Ninja for all of our commercial operations and that certainly continues to drive maintenance IMHO.

**Comment by thibaultmeyer** [comment]
Glad to hear it,

If you want, I can sort out the different issues that are already open by adding labels and assigning the right people.

Maybe I can also close very old issues if they are not bug related. I can close old milestones too and we can see to create new ones.


Proposal for labels

- priority/critical
- priority/medium
- priority/low
- priority/maybe
- kind/question
- kind/bug
- kind/breaking
- kind/feature
- kind/refactor
- kind/security
- kind/regression
- kind/enhancement
- kind/documentation
- kind/lint
- kind/build
- kind/performance
- kind/proposal

@jjlauer @raphaelbauer, Does this sound good to you?
