### ISSUE TITLE
"Expression xy is undefined" in template rendering

### ISSUE THREAD

**Issue by roughy** [ninjaframework/ninja#77]
Obviously this error message is very helpful by finding and solving problems regarding undefined variables.

Unfortunately it has 2 not so nice behaviours:
1. The formatting in the browser is unreadable
2. If this error occurs within a html tag or within the head tags the browser just shows a plain white page.

To reproduce the problem please try the following template without setting "redirectUrl":

``` html
<html>
    <head>
        <meta http-equiv="refresh" content="3;url=${redirectUrl}">
        <title>Success</title>
    </head>
    <body>
          I'll redirect you.
    </body>
</html>
```

My suggestion is to skip the whole html from the template and show only the error within pre-tags. Or even better with a nice and colourful presentation.

**Comment by raphaelbauer** [comment]
errors are now shown inside the browser in dev mode...
