### ISSUE TITLE
Ninja Framework as a dependency doesn't get resolved.

### ISSUE THREAD

**Issue by javajack** [ninjaframework/ninja#78]
Which maven repo Ninja Framework is hosted on ? I downloaded the source for demo app and tried to run the app but maven is not able to find the Ninja Framework jar as a part of dependency ?

**Comment by raphaelbauer** [comment]
On Sun, Mar 3, 2013 at 9:01 AM, Rakesh Waghela notifications@github.comwrote:

> Which maven repo Ninja Framework is hosted on ? I downloaded the source
> for demo app and tried to run the app but maven is not able to find the
> Ninja Framework jar as a part of dependency ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/reyez/ninja/issues/78
> .

Not sure how you downloaded the source code. Ninja Jars are hosted on maven
central. You should be able to get them without any special settings.

How did you download the demo code? And if you look into the pom.xml - what
version of ninja-core is required?

Two additional hints:
1) You can always clone the repository and checkout the develop branch -
then run a "mvn clean install" to get the latest jars locally. => then go
to ninja-core-demo and run mvn jetty:run to play around with ninja
2) If you want stable versions make sure you checkout the correct tag. 1.1
is eg. ninja-1.1 (https://github.com/reyez/ninja/tree/ninja-1.1).

Hope that helps :)

I have to admit it is a bit complicated at the moment. This will change
once we got a nice Ninja Maven Archetype...

Best,

Raphael
