### ISSUE TITLE
Inconsistency in message formatting 

### ISSUE THREAD

**Issue by pthum** [ninjaframework/ninja#95]
There's an inconsistency in the message formatting.
The "FlashCookie" uses the String.format-method to format a message with arguments. Thereby you have to use e.g. "%s" as placeholder in your messages. 
The "Messages" uses instead the MessageFormat.format (from java.text), which expects placeholders from kind "{0}". 
To my mind, the MessageFormat-version is a very nice one, because you don't have to care about the types of the arguments. On the other hand, the String.format seems to be a bit faster ( http://jevopisdeveloperblog.blogspot.de/2009/09/stringformat-vs-messageformatformat-vs.html ).

**Comment by raphaelbauer** [comment]
Hi,

can you please have a look at: https://github.com/reyez/ninja/pull/96

It fixes the issue and also improves some other things.

Let me know what you think :)

Thanks!

Raphael
