### ISSUE TITLE
Provide more comfortable rendering

### ISSUE THREAD

**Issue by pthum** [ninjaframework/ninja#97]
If you want to render one object, you can comfortably do this by giving the object to the Results.render(..)-Method. But if you have more than one object, you need to create a map, put the objects in and pass this map to the render-method.
I suppose that the need for this procedure will increase with #96 .
To my mind, we should provide a more comfortable way to pass more than one object to the template, but i dunno how to solve this.
In the rendering process, the templateengine will definitely create a map to put all implicit variables. Maybe we can use this? 
My Idea is to have a map in the Result-class, where objects can be added by using "render(object)" or "put(object)" or sth. (thereby, the classname will be added as key, like its done now by the templateengine) and also can be added by using sth like "render(key, object)" to chose explicitly an own key (this may be useful if you have more than one object of the same class you want to render).
Maybe its somehow possible to pass all objects in a single row (like "return Results.html().render(object1).render(object2).render(object3);" )?
The templateengine then takes the map of the result to put the other implicit variables in.
Are there any side-effects expectable?
Any suggestions?

**Comment by raphaelbauer** [comment]
Hi pthum,

I think you are right. I played around a bit: https://github.com/ninjaframework/ninja/compare/feature-render-multiple-objects

Would be great getting feedback. You can now chain render().render().render() and the templating engine will get a map (as usual).

The only thing I don't like right now is the following code:

Results.render(new SimpleImmutableEntry("myObject1", myObject1);
Results.render(new SimpleImmutableEntry("myObject2", myObject2);

=> If you are rendering multiple objects of the same type the simple "toLowerCamelcase" key mapping does not work. Right now you can fix that using an Entry.. but the code looks clumpsy... Maybe we should change the signature to render(Object ... object) ...
hmm...

Does this go roughly into the right direction?

**Comment by raphaelbauer** [comment]
I updated the pull request... you can now do:

```
   Result result = new Result(200);
    result.render("object1", object1);
    result.render("object2", object2);
```

eg in your ftl.html files you can then use ${object1.xyz} to access your objects... no need for a map and no need for an entry...

Any feedback on the code would be great :)

**Comment by pthum** [comment]
this is very cool and exactly what i've thought.
great work :+1:
